caproto/_commands.py
caproto/_dbr_types.py
caproto/_hub.py
test_with_motorsim.py

Nuke any/all if desired - I did my normal thing and read as little as possible to get it implemented 😄

ENH: subscriptions with subpar adherence to de facto coding standards

---

README.md
doc/gen_graphs.py
test_with_pyepics.py

ENH: simple graphviz transition digraphs

---

caproto/_commands.py

Refactor payload to EventAddRequestPayload
Ref https://github.com/epics-base/epics-base/blob/3.16/src/ca/client/tcpiiu.cpp#L1561

FIX: event_add_request payload mask is in upper 16-bits of 32-bit int

---

caproto/_commands.py
caproto/_hub.py
caproto/_state.py

Some fixes based on what the linter found as well
Will squash if desired

Import cleanup and PEP8 fixes

---

caproto/_state.py

Not sure about best practice here, but submitting PR for reference
Interesting note about rsrv versus CAS: 
http://www.aps.anl.gov/epics/tech-talk/2013/msg00023.php
Reference about unsolicited version reply: 
https://github.com/epics-base/epics-base/blob/3.16/src/ioc/rsrv/caservertask.c#L1454

MNT: Unsolicited VersionReply on connect with rsrv

---

caproto/examples/repeater.py
doc/source/basics.rst

This isolates the change in #10 that is causing Travis to hang. Locally it works fine (and seems more correct than current `master` to me). Not sure yet what's wrong here.

FIX: Do not rebroadcast RepeaterRegisterRequest.

---

doc/gen_graphs.py
doc/source/api.rst
doc/source/basics.rst
doc/source/conf.py
doc/source/index.rst

Auto-builds @klauer's beautiful state machine graphs and puts them into the docs.

DOC: Auto-build state machine graphs.

---

.coveragerc
.gitignore
.travis.yml
caproto/_state.py
docs-requirements.txt
run_tests.py
test-requirements.txt
tests/test_examples.py

This runs the two client examples, putting at 38% coverage. It's a start.

Add some py.test tests and set up coverage and codecov.

---

doc/source/index.rst

* Rephrase "why do this" to include more specifics.
* Remove not-yet-true claim about catvs, which we may not get to soon.

DOC: Update front page.

---

caproto/_commands.py
tests/test_serialization.py

A simple test with a handful of fixes found already.
Payload comparison is failing currently (and is an important TODO for this PR).

TST/FIX: Serialization round trip

---

caproto/_commands.py

Do not merge. This is likely to take some work.

WIP: Use __slots__ to make Messages lighter.

---

.travis.yml
caproto/_commands.py
caproto/_dbr.py
caproto/_hub.py
caproto/thread/client.py
tests/pvnames.py
tests/test_serialization.py
tests/test_thread_pv.py

This builds on #34 and re-uses tests from pyepics

Test PV drop-in class

---

.travis.yml
circle.yml

Dying-on-the-couch PR numero 1

CI: allow py.test to capture stdout/stderr due to current verbosity

---

caproto/threading/client.py

This was in #51 in a slightly different version.

MNT: use partition to find end of null-terminated strings

---

caproto/_commands.py
caproto/_data.py
caproto/_dbr.py
caproto/curio/server.py
doc/source/api.rst
doc/source/basics.rst
doc/source/curio-server.rst
doc/source/index.rst
tests/test_examples.py

* DBR_GR_{*}
* DBR_STSACK_STRING
* DBR_CLASS_NAME
The framework was there, but not support in the server/payload-handling functions. This should cover the rest.
... questionable design decisions included as usual (and subject to negotiation)
... and failing travis due to `ca_test` not being there - will try again some other time.

ENH: Remaining DBR types

---

tests/test_nonet.py

No surprises here. Extra tests for due diligence.

TST: Test that all the states are what we expect through a transaction.

---

caproto/_data.py
caproto/_dbr.py
caproto/_hub.py
caproto/curio/server.py

Primarily a fix for the server, but also adds dbr.AccessRights

FIX: access rights should check hostname/username

---

caproto/asyncio/repeater.py
caproto/threading/client.py

Fix repeater

---

doc/Makefile
doc/source/basics.rst
doc/source/release-notes.rst

Also adds fail on warnings back

Hot-fix docs to work with new repeater

---

caproto/threading/client.py
tests/test_threading_client.py

I think this should fix some intermittent failures we have seen on Travis.

TST: Fix race condition in threading tests.

---

caproto/_commands.py
caproto/_data.py
caproto/_dbr.py
caproto/_utils.py
tests/test_curio_server.py
tests/test_examples.py

Functionality based on what's in EPICS base, as of yet untested plane commits. Some tests may need to be modified to reflect the logic built into the alarm (specifically transient/severity acknowledge)

FIX: alarm acknowledgement logic

---

.ci/run-epics-iocs.sh
.ci/run-pyepics-simulator.sh
.travis.yml
setup_local_dev_env.sh

CI: Fix CI so that simulator starts.

---

caproto/threading/client.py

Only type-check first entry for str that needs to be encoded.

PERF: assume input is homogeneous type

---

caproto/threading/client.py

Small fixes with undefined variables left in after the refactor

Thread client fixes/tweaks

---

.ci/run-epics-iocs.sh
.travis.yml
caproto/tests/conftest.py
caproto/tests/test_bench.py
caproto/tests/test_curio_server.py
caproto/tests/test_examples.py
caproto/tests/test_repeater.py
caproto/tests/test_thread_pv.py
caproto/tests/test_threading_client.py
caproto/tests/test_threading_pv.py
caproto/threading/client.py
codecov.yml

Original misleading title/branch name was for tweaking the thread client again (only one indentation fix here)
Fixes #104

CI: fix codecov, pytest 3.3.0, and tweak tests

---

.ci/install-epics-base.sh
.ci/install-epics-modules.sh

CI: aps.anl.gov SSL certificate has expired; switch to github links

---

caproto/asyncio/repeater.py
caproto/tests/test_examples.py

FIX: RepeaterAlreadyRunning check on Linux

---

caproto/_broadcaster.py

Needs tests. Posting for discussion.

ENH: Track whether registration has been attempted separately from confirmed.

---

caproto/_data.py
caproto/_utils.py
caproto/curio/server.py
caproto/tests/_asv_shim.py
caproto/tests/test_bench.py

Brought in from the old trio PR
* Support EPICS_CAS_INTF_ADDR_LIST
* Support create_many directly on the curio client context
* Some pytest/asv fixes

Misc fixes

---

caproto/threading/pyepics_compat.py

Prevents race condition of
- am I connected?
- (connection happens, flips event)
- clear event
- wait on event forever

FIX: protect more things with lock

---

caproto/_dbr.py
caproto/sync/client.py

The sync client improvements were made in the course of debugging.

FIX: Crucial typo (omitted special type) and unrelated sync client improvements

---

.travis.yml
caproto/_circuit.py
caproto/_utils.py
caproto/examples/thread_client_simple.py
caproto/tests/conftest.py
caproto/tests/test_pyepics_compat.py
caproto/tests/test_threading_client.py
caproto/threading/client.py
caproto/threading/pyepics_compat.py
setup.py

~WIP DO NOT MERGE~
This turned out to be a total rewrite of the threading client with a clearer API, more thoughtful locking, and much more thorough tests.

Locks locks locks

---

.travis.yml
caproto/tests/conftest.py
caproto/tests/test_threading_client.py
pytest.ini

CI/TST: Harden tests and tweak pytest reporting on Travis-CI

---

caproto/_circuit.py
caproto/_utils.py
caproto/sync/client.py
doc/source/api.rst

A possibility - no hard feelings if not merged

REF: sentinel -> enum

---

caproto/curio/client.py
caproto/threading/client.py
caproto/trio/client.py
doc/source/async-clients.rst
doc/source/command-line-client.rst
doc/source/threading-client.rst

API: Client Contexts instantiate a fresh SharedBroadcaster by default.

---

caproto/_commands.py
caproto/_utils.py
caproto/asyncio/server.py
caproto/curio/server.py
caproto/examples/trio_server_simple.py
caproto/server/common.py
caproto/server/server.py
caproto/sync/repeater.py
caproto/tests/conftest.py
caproto/trio/server.py
doc/source/ports.rst
doc/source/references.rst

Closes #222. ~~More accurately, it _will_ once it's ready to merge -- right now this is just docs to help me sort out what to do.~~

FIX: Fix interface and port configuration.

---

caproto/examples/defaultdictserver.py
caproto/examples/spoof_beamline.py

I merged #264  a little too quickly -- there were ``flake8`` errors. This fixes
those and does other minor stuff.

REF/STY/DOC: Follow-up on #264

---

caproto/asyncio/server.py
caproto/ioc_examples/barcode_reader.py
caproto/ioc_examples/currency_conversion.py
caproto/ioc_examples/currency_conversion_polling.py
caproto/ioc_examples/io_interrupt.py
caproto/server/server.py
caproto/tests/test_examples.py

Pin several examples to curio
closes #225

MNT: switch examples to using asyncio by default

---

caproto/_data.py

Confirmed in epics-base source that this is how epics-base works.

FIX: Do old-style masking based on absolute not relative change.

---

caproto/_utils.py

A few spots where I assume you had never actually seen a `EPICS_CA_REPEATER_PORT` environment variable. With this fix I can now successfully read **after** sourcing the standard PCDS `EPICS` setup script.

FIX: Port number needs to be an integer

---

caproto/ioc_examples/currency_conversion.py
caproto/ioc_examples/currency_conversion_polling.py
caproto/ioc_examples/io_interrupt.py
caproto/server/server.py

ENH: Consolidate async lib whitelisting in ioc_arg_parser.

---

caproto/tests/test_examples.py
caproto/tests/test_pyepics_compat.py
doc/source/install.rst

TST/DOC: Add an env var for skipping motorsim tests.

---

caproto/server/common.py

FIX: Issue beacons faster at startup.

---

doc/source/index.rst
doc/source/protocol-compliance.rst

DOC: Document protocol compliance and feature parity.

---

caproto/threading/pyepics_compat.py

Bug was introduced in 7f7f2e43, #329

FIX: Update internal calls to new sig of _accces_rights_changed.

---

.travis.yml
caproto/_utils.py
caproto/asyncio/server.py
caproto/ioc_examples/states.py
caproto/tests/test_channel_filters.py
caproto/tests/test_utils.py
caproto/threading/client.py
docs-requirements.txt

Still on the path to better CI...

Fix epics_ca_addr_list warning

---

caproto/asyncio/server.py
caproto/curio/server.py
caproto/ioc_examples/startup_and_shutdown_hooks.py
caproto/server/common.py
caproto/server/server.py
caproto/tests/test_examples.py
caproto/trio/server.py

Adds a shutdown hook symmetric to the startup hook.
Needs a test.

ENH: Add server shutdown hook.

---

doc/source/install.rst

EPICS on your iPhone has never been so easy.

DOC: add iOS/Pythonista installation notes

---

caproto/asyncio/server.py
caproto/server/common.py
caproto/tests/test_server.py

FIX: Fix asyncio command queue backlog bug and win32 bug.

---

caproto/_constants.py
caproto/_data.py
caproto/asyncio/server.py
caproto/curio/server.py
caproto/server/common.py
caproto/trio/server.py

See #323 for progress updates.

FIX: Address corner cases and high-load tuning with acctst

---

caproto/_circuit.py
caproto/_constants.py
caproto/sync/repeater.py
caproto/threading/client.py
doc/source/protocol-compliance.rst
doc/source/threading-client.rst

Submitted for discussion. Tested interactively.
Closes #365 
Closes #371 
Closes #246

ENH: Add search backoff, cancellation, and manual search_now().

---

caproto/_broadcaster.py
caproto/_circuit.py
caproto/threading/client.py
caproto/threading/pyepics_compat.py

See #383 and #385. The important commit is 048042ad.
This cherry-picks other logging fixes and secondary optimizations accumulated
in #383 during our search for the main issue.

PERF/CLN: Use SO_KEEPALIVE and TCP_NODELAY

---

caproto/_data.py
caproto/tests/test_server.py

OK - this could be squashed as the first 2 commits are using a completely different approach than the last commit. I think the new approach is much better as I noted below.
Tests are passing, ready for review.

FIX: data picklability

---

caproto/tests/test_pyepics_compat.py
caproto/threading/pyepics_compat.py

For feature parity with upstream. 
Note that this has not yet been merged in pyepics, and we should wait until that happens first.

ENH: support get_with_metadata in pyepics_compat.PV

---

doc/source/loggers.rst
doc/source/release-notes.rst

Includes one unrelated documentation-cleanup commit as well.

DOC: Add release notes for v0.2.3.

---

caproto/threading/client.py

Closes #409
Tested interactively. Could use some real tests...gotta think about how to
mock this behavior effectively on a test server.

ENH: Add 'attempts' and 'timeout' on Context, PV.

---

caproto/ioc_examples/dynamic_pvgroups.py

This seems to keep coming up. How does this quick example look?

ENH: add semi-dynamic PVGroup example

---

azure-pipelines.yml
azure_env.sh
setup_development_network.sh
setup_local_dev_env.sh

Auto-generated azure-pipelines.yml
Separate (nonfunctional) work going on in klauer/caproto@azure

CI: initial azure test

---

.codecov.yml

Keep the X-or-checkmark in the status pane next to Travis, but
suppress the big comment.

CI: Add codecov configuration file.

---

caproto/_array_backend.py
caproto/_commands.py
caproto/_data.py
caproto/_utils.py
caproto/tests/test_examples.py
caproto/threading/client.py

No idea why this worked before under cpython...

FIX: several things for pypy3

---

caproto/threading/client.py
doc/source/index.rst
doc/source/iocs.rst
doc/source/release-notes.rst
doc/source/threading-client.rst

Also includes documentation and docstring updates

DOC: Release notes for v0.3.0

---

doc/source/iocs.rst

Bug was introduced in f2b1ab7e3

DOC: hotfix IOC examples

---

caproto/threading/client.py

This fixes a bug where if the user searches for many PVs
simultaneously (for example, when connecting a complex ophyd device)
the early requests will be reset on each subsequent request an
interval much shorter than MIN_RETRY_SEARCHES_INTERVAL.

FIX: only re-send search request if we have not sent it recently

---

caproto/server/server.py

asyncio as default in help docs

MNT: modify help docstring

---

caproto/server/records.py

FIX: scan field write in server

---

README.md

Fixed broken link to documentation in README.md file

Fixed broken link to Caproto documentation

---

caproto/_broadcaster.py
caproto/tests/test_core.py

Thanks @RussBerg for finding this.

FIX: error message did not match code

---

doc/source/index.rst
doc/source/threading-client.rst

I looked over the docs last night and found some minor errors.

Copy-editing docs

---

doc/source/iocs.rst

Paraphrasing @klauer from #518:

Explain async_lib.library.sleep.

---

test-requirements.txt

On conda-forge: pytest-benchmark-3.2.3
On pypi: https://pypi.org/project/pytest-benchmark/

TST: pytest_benchmark -> pytest-benchmark

---

docs-requirements.txt

BLD: unpin sphinx

---

caproto/threading/client.py

Closes #588 
* Attempt to remove `id_to_socket`
See a way to remove `socket_to_id` as well?

REF/CLN: selector in threaded client

---

doc/source/release-notes.rst

@klauer Would you add a commit summarizing the improvements and changes associated with your work on records?

Release notes for 0.5.0

---

caproto/ioc_examples/enums.py

ENH: add mbbi example to enum IOC

---

caproto/threading/client.py

Closes #539 
Before:
It is not possible to subscribe with a callback if a PV is not connected.
```py
In [1]: from caproto.threading.client import Context                                                                                                                                          
ct
In [2]: ctx = Context()                                                                                                                                                                       
In [3]: pv, = ctx.get_pvs('simple:A')                                                                                                                                                         
In [4]: pv …
```

Allow subscription before connection.

---

caproto/tests/test_threading_client.py
caproto/threading/client.py

Closes #607
Thanks again, @pklaus!

Avoid duplicate registration of callbacks.

---

caproto/asyncio/utils.py

I think this is a reasonable trade-off from the previous implementation: you must create the queue in an async function so it knows which loop to use.
If not, we can return to the 
```
def create_queue_class(loop):
class AsyncioQueue:
...
```
style we had before.

FIX: asyncio queue put must use run_coroutine_threadsafe

---

.pre-commit-config.yaml
caproto/pva/__init__.py
caproto/pva/_annotations.py
caproto/pva/_circuit.py
caproto/pva/_core.py
caproto/pva/_data.py
caproto/pva/_dataclass.py
caproto/pva/_fields.py
caproto/pva/_messages.py
caproto/pva/_normative.py
caproto/pva/_pvrequest.py
caproto/pva/_state.py
caproto/pva/prototype/client.py
caproto/pva/sync/client.py
caproto/tests/test_pva.py

Mypy-related fixes + various other cleanup.
No changes to base caproto, will self-merge.

REF/CLN: pva refactoring and cleaning, continued

---

.pre-commit-config.yaml
caproto/_utils.py
caproto/pva/_broadcaster.py
caproto/pva/_circuit.py
caproto/pva/_core.py
caproto/pva/_data.py
caproto/pva/_dataclass.py
caproto/pva/_fields.py
caproto/pva/_functools_compat.py
caproto/pva/_messages.py
caproto/pva/_pvrequest.py
caproto/pva/commandline/put.py
caproto/pva/ioc_examples/basic.py
caproto/pva/server/common.py
caproto/pva/sync/client.py
caproto/tests/test_pva.py
caproto/tests/test_pva_circuit.py
caproto/tests/test_pva_pvrequest.py
caproto/tests/test_pva_server.py

Progress from past few weeks; will merge if tests pass
* Preliminary put support in server
* Singledispatch is nice
* New message -> subcommand style
* Channel message handling
* Cleaning, fixes, mypy pacification where possible

[PVA] Progress update

---

.travis.yml
azure-pipelines.yml

Just a test; nothing to see here
(will it actually pass?)

CI: parallelize?

---

setup.py

Hoping this will close 🤞  #665 
Ref: https://packaging.python.org/guides/distributing-packages-using-setuptools/#manifest-in

BLD: fix package data for wheels

---

caproto/ioc_examples/setpoint_rbv_pair.py
caproto/server/server.py
caproto/tests/view_leaks.py

ENH/FIX: get_pv_pair_wrapper kwargs

---

caproto/ioc_examples/enums.py
caproto/server/server.py

Closes #520 
Adds a greatly simplified syntax for enums with less room for error.

ENH: add support for IntEnum values with pvproperty

---

caproto/ioc_examples/dynamic_calc.py
caproto/ioc_examples/too_clever/dynamic_calc.py

The idea is that you can set a python expression to a PV and the
IOC will dynamically create / remove channels to have the PV names
match the variable in the expression.
Still needs some work (like being able to actually remove the old
channels!) and to sort out if this is just cute or actually a useful
idea.

ENH: a "clever" IOC example which dynamically creates pvproperties based on a formula

---

.travis.yml
CONTRIBUTING.md
MANIFEST.in
caproto/docs/templates/autosummary/class.rst
caproto/docs/utils.py
caproto/pva/ioc_examples/advanced.py
caproto/pva/ioc_examples/group.py
caproto/pva/ioc_examples/normative.py
caproto/pva/server/magic.py
caproto/tests/test_pva_dataclass.py
caproto/tests/test_pva_server.py
doc/source/async-clients.rst
doc/source/cookiecutter.rst
doc/source/index.rst
doc/source/pva/api.rst
doc/source/pva/clients.rst
doc/source/pva/index.rst
doc/source/pva/iocs.rst

* asyncio client doc outline / first attempt
* cookiecutter doc outline / first attempt
* caproto-pva doc outline / first attempt
Closes #630 
Closes #670
Closes #677  
Part of #674

DOC: docs docs docs (asyncio client, cookiecutter, pva)

---

caproto/server/stats.py

FIX: filter snapshots in delta/diff comparison as well

---

doc/source/index.rst
doc/source/release-notes.rst

DOC: v0.7.0 release notes

---

caproto/threading/client.py

It seems during shutdown Python knocks oven the executor before we do
causing the notifications of channel disconnect to fail.
As this happens on process exit, just accept it and move on.
This empirically works, but I do not understand why as the code in the callbacks is in fact running before we get to the shutdown line!

FIX: be forgiving about dead Executors with dead circuits

---

doc/source/index.rst

Questions about whether it makes sense to "bet" on caproto and invest in caproto-based infrastructure have come from multiple facilities in the past couple months. It makes us happy to learn about caproto adoption, but we worry about caproto become _too_ popular to ~2 core devs to support mostly in our evenings/weekends.

Add clear expectation-setting language.

---

caproto/examples/benchmark_connections.py
doc/source/shark.rst

Captured from https://gist.github.com/danielballan/10f391a26ee1d015b1806aa6f788c721

Add pcap example.

---

caproto/_circuit.py
caproto/_commands.py

FIX: ChannelType(data_type) for command init

---

caproto/_broadcaster.py
caproto/_commands.py
caproto/server/common.py

ENH: RemoteProtocolError on Commands[role][id] KeyError

---

caproto/asyncio/client.py
caproto/threading/client.py

I'll get this one right eventually. Let's see how this does.

FIX: call correct disconnect() method

---

.ci/install.sh
.github/workflows/docs.yml
.github/workflows/testing.yml
doc/source/iocs.rst
requirements-test.txt

(There may be a bit of push-to-master thrashing -- limited to `.github`, or a new PR will be made -- to get this working 100%; apologies in advance to those who haven't muted this repo just yet)

CI: build and deploy docs with GH actions

---

.gitignore
MANIFEST.in
caproto/_data.py
caproto/docs/templates/autosummary/class.rst
doc/source/_static/inheritance.css
doc/source/conf.py
doc/source/server_api.rst

DOC: add some manual inheritance diagrams, plus autosummary ones

---

doc/source/release-notes.rst

I should probably leave this open until it's _really_ done this time...

DOC: update release notes for recent PRs

---

caproto/threading/pyepics_compat.py

FIX: byte value leaking through in pyepics_compat for DBR_STRING

---

caproto/ioc_examples/fake_motor_record.py

Make it easy to set user limits, to mock out more of the EPICS database.

ENH: provide defaults for user limits

---

caproto/commandline/cli_print_formats.py
caproto/ioc_examples/fake_motor_record.py
caproto/threading/pyepics_compat.py

WIP: Initial implementation of caget_many timeout for review. Considering using this PR to utilize [batching](https://caproto.github.io/caproto/v1.0.0/threading-client.html#batched-requests) in caget_many. 
Closes #805

FIX: Timeout ignored in pyepics_compat's caget_many

---

.github/workflows/pypi.yml
.github/workflows/testing.yml

CI: fix GitHub actions pypi uploading workflow

---

README.md

DOC: add content to readme

---

caproto/tests/test_pyepics_compat.py
caproto/threading/pyepics_compat.py

fix pyepics compat automonitor sub

---

.github/workflows/testing.yml
azure-pipelines.yml

Based on #854 - but I don't want to sully the ✅ with a ❌

TST: Add Python 3.13 to the test matrix

---

caproto/tests/test_pyepics_compat2.py
caproto/threading/pyepics_compat.py

Alternative to https://github.com/bluesky/ophyd/pull/1186

FIX: convert arrays to native endianess in pyepics_compat

---

.github/workflows/docs.yml
.github/workflows/flake8.yml
.github/workflows/pypi.yml
.github/workflows/testing.yml

* codecov 3 -> 5
* setup python v5
* upload, download artifact v4
* checkout v4
* Test suite coverage artifact name decollision

CI: update actions to fix continuous integration
