caproto/caproto

caproto/_hub.py
caproto/_state.py

This may not be how it was intended to be used - here for discussion.
Should instead the virtual circuit be monitoring what happens to the
channels instead of the channels themselves?

ENH: add state_changed callback on channels

---

README.md

Everything in TODOs is either done or documented elsewhere. I'm removing it to make the README neater -- I want people to click on "Documentation," not get lost in our old laundry list.

DOC: Remove TODOs from README.

---

caproto/_state.py

The state machines needed some code cleanup for readability and
allowed some transitions that in fact were not legal (artifacts of
early misunderstandings in the design process).
Amazingly, all the tests still pass in one try!
I sure hope Travis agrees.

Remove extraneous transitions and add missing ones.

---

caproto/examples/repeater.py

* ~~Don't rebroadcast the original registration request. (This rebroadcast is not expected by the docs, and it's why the basics.rst example is broken.)~~ Merged separately in #12 
* Respect the EPICS_CA_REPEATER_PORT env var.
* Add comments based on current understanding of CA Repeater operation. Not all of this reflected in this Python implementation yet.

Refine repeater.

---

caproto/_hub.py

I believe that the traceback report in #42 can only occur if the hub processes
an emtpy datagram (``b''``). This will cause it to respond with ``NEED_DATA`` instead of an exception.
Closes #42

FIX: Handle rare case of empty datagram.

---

caproto/_dbr.py
caproto/threading/client.py

I think this is what we agreed on yesterday (and it's what is explained in the comments for this function) but somehow the implementation got lost. All the same tests pass; this is just a quality-of-life measure.

FIX: Parse CHAR waveform as bytes not numpy array of chars.

---

caproto/_dbr.py
caproto/threading/client.py

Reverts danielballan/caproto#51
Consensus changed. Although bytes are a simpler way to represent a waveform of characters, having *everything* return as a numpy array is nicer, and it's very easy to convert to bytes if desired.

Revert "FIX: Parse CHAR waveform as bytes not numpy array of chars."

---

caproto/_hub.py
caproto/curio/client.py
caproto/curio/server.py
caproto/threading/client.py
doc/source/basics.rst
doc/source/curio-client.rst
tests/test_examples.py
tests/test_hub.py

Astoundingly, this rename is made at the request of @tacaswell.
He argues that `ServerChannel.disconnect()` and `ClientChannel.clear()` is a weird asymmetry in EPICS naming that we should hide for consistency at the client/server layer or probably at the hub layer too. I can see it either way, and I'm perfectly happy to change it at this stage.

API: Rename Channel.clear() -> Channel.disconnect()

---

caproto/threading/client.py
tests/test_examples.py
tests/test_threading_pv.py

This fixes an accidental API mismatch with pyepics: get() and put() should return ``command.data``, not ``command``.

ENH/TST: Support put completion in threading client.

---

caproto/_commands.py
caproto/_dbr.py

Before:
```
ReadNotifyResponse(data=array([1], dtype=int16), data_type=8, data_count=1, status=1, ioid=0, metadata=<caproto._dbr.DBR_STS_INT object at 0x10b8ab598>)   
```
After:
```
ReadNotifyResponse(data=array([1], dtype=int16), data_type=<ChannelType.STS_INT: 8>, data_count=1, status=1, ioid=0, metadata=DBR_STS_INT(status=<AlarmStatus.HWLIMIT: 11>, severity=<AlarmSeverity.MAJOR: 2>)) 
```

ENH: Improve DBR repr and use IntEnums in commands.

---

caproto/threading/client.py

Reverts NSLS-II/caproto#118 in favor of https://github.com/NSLS-II/caproto/pull/112/commits/724b32d375712a8778b5cbb11e29f403e984b5b6

Revert "PERF: assume input is homogeneous type"

---

caproto/curio/server.py
caproto/threading/client.py

- The UTF-8 encoding is not an appropriate default for EPICS (and often blows up on real cases).
- Now the encoding is configurable through an ENV var.

FIX: Standardize string encoding and expose ENV var.

---

caproto/curio/high_level_server.py
caproto/examples/curio_server_currency_conversion.py
caproto/examples/curio_server_high_level.py
caproto/examples/curio_server_high_level_subgroup.py
doc/source/examples/custom_write.py
doc/source/examples/inline_style.py
doc/source/examples/macros.py
doc/source/examples/reading_counter.py
doc/source/examples/simple_ioc.py
doc/source/index.rst
doc/source/iocs.rst

* Adds `pvproperty`, a property-like way of defining a caproto IOC's structure
* Adds `PVGroupBase` which allow for grouping of `pvproperty` and other `PVGroupBase`s
* Adds `SubGroup`, the class to use when nesting `PVGroup`s
There are 3 simple examples there, which should be the target of your criticism/suggestions more so than the server source itself. I think it's relatively clean. Let me know what you think, in any case!
Things that might not be obvious:
* If you don't specify a `getter` or a `putter`-handler in your `pvproperty`, the group itself handles the event in its `group_read` and `group_write` functions, respectively
* In all the get/put handlers, `self` refers to the group, as you'd expect, whereas `instance` refers to the `ChannelData` instance
* Prefixes are similar to how …

WIP/ENH: High level server idea

---

.circleci/config.yml
.circleci/start-tmux.sh
caproto/tests/_asv_shim.py
caproto/threading/client.py
setup_local_dev_env.sh

This is in a much better spot now, but there's still a lot left to do on the time sink that is CI.
* The tests are running natively in a docker image I created which contains EPICS 3.14, 3.15, 3.16, motor, areaDetector, and PVA libraries (using [epics-on-travis](https://github.com/klauer/epics-on-travis) and [caproto-docker](https://github.com/klauer/caproto-docker)).
* IOCs run on tmux in the background when started up
* As-is, only one configuration is actually tested (no conda, so 3.6 only)
**TODO**

CI: update circleci configuration

---

caproto/sync/repeater.py

It's nice to have a way to know that the repeater has started.
Previously even verbose logging would not tell you this. In this PR,
the `-q/--quiet` flag suppresses this message.

ENH: Issue a log message when the repeater is up.

---

.travis.yml

This may increase test reliability, as procserv will automatically restart the crashing IOC (pyepics test IOC on 3.16/7)
Let's merge this and rebase #161 on top (a couple commits from there are cherry-picked here).

CI: run IOCs/simulator on procserv

---

caproto/_circuit.py
caproto/sync/client.py
caproto/tests/test_threading_client.py
caproto/threading/client.py

Also refactors. See commit message.

FIX: Use non-goofy defaults for host and client name in threading client.

---

caproto/threading/client.py

Fixes NSLS-II/ophyd#524 by avoiding callback deadlock
Solution was the first that came to mind (ophyd pseudo positioner tests all pass locally) - eventually smarter handling using a thread pool or throwing out monitors that are too far backlogged may be worthwhile.

FIX: threading callback queue

---

caproto/sync/client.py

This hopefully should make the CLI tests fail a bit less frequently.
In summary:
* multiple search requests (could use improvement)
* registration response not waited for

REF: rework sync client search/register a bit

---

caproto/_utils.py
caproto/curio/server.py
caproto/tests/test_utils.py
caproto/trio/server.py

This does two things:
1. Warns when `*_ADDR_LIST` is set but `*_AUTO_ADDR_LIST` is unset or 'yes', such that
the content of `*_ADDR_LIST` will just be ignored.
2. Includes the name of the interface in the error message.
Example failure with two helpful hints in it now, thanks to this PR:
```
$ spoof-beamline
/Users/dallan/Documents/Repos/caproto/caproto/_utils.py:134: UserWarning: EPICS_CA_ADDR_LIST is set but will be ignored because EPICS_CA_AUTO_AUTO_ADDR_LIST is not set to 'no'.
warn("EPICS_CA_ADDR_LIST is set but will be ignored because "
/Users/dallan/Documents/Repos/caproto/caproto/_utils.py:138: UserWarning: EPICS_CAS_BEACON_ADDR_LIST is set but will be ignored because EPICS_CAS_AUTO_BEACON_ADDR_LIST is not set to 'no'.
warn("EPICS_CAS_BEACON_ADDR_LIST is set but will be ignored …
```

Make beacon send failures produce more helpful errors.

---

appveyor.yml

Possibly of interest to @johnsinsheimer.

WIP: Test on Windows with appveyor

---

caproto/threading/client.py

I got a 'dict changed size during iteration' error when using the threading
client in the wild. I have never seen it before or reproduced it since, but I
believe this will fix it.

FIX: Lock unanswered_searches when modifying or iterating over it.

---

caproto/asyncio/server.py

``socket.shutdown`` has a required argument. Because this happens in a cleanup
step it was not being caught but it generated error messages in the test logs.

FIX: Shutdown socket properly.

---

setup.py
test-requirements.txt

Closes https://github.com/NSLS-II/caproto/issues/209
This partitioning of dependencies anticipates three use cases:
* Give me nothing but caproto (`pip install caproto`)
* Give me everything (`pip install caproto[complete]`)
* Skip the async libs but give me a full-featured sync, threading,
and pyepics-compat clients
(`pip install caproto[standard]`)
We also have `pip install caproto[async]` but I'm not sure how
popular that will be.

BLD: Use extras_require to implement optional dependencies.

---

caproto/_circuit.py

This needs some testing, but it works against a real v12 server that was failing before.
The fix is to:
- carry the version information on the circuit (can you have mixed version channels on the same circuit?)
- aggressively update the protocol version if we find out that it is a lower version than we asked for
- break the API on `_BaseChanel` to get the version from the circuit
Maybe we should prevent a create channel command from going out until we have a VersionResponse?

Fix v12 support

---

caproto/curio/client.py
caproto/trio/client.py

Verifying warnings in pytest is easy, but verifying that WARNING log
messages were sent is harder (seems to require third-party plugins, and
the support does not look great).
So I tested this interactively. Will circle back for unit testing of
warnings in general.

ENH: Warn on duplicate search results in trio and curio clients.

---

caproto/_data.py

Example of the issue that this solves:
```
File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/curio/kernel.py", line 736, in _run_coro
trap = current._send(current.next_value)
File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/curio/task.py", line 167, in _task_runner
return await coro
File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/curio/network.py", line 106, in run_client
await client_connected_task(client, addr)
File "/home/travis/build/NSLS-II/caproto/caproto/server/common.py", line 525, in tcp_handler
await circuit.recv()
File "/home/travis/build/NSLS-II/caproto/caproto/server/common.py", line 68, in recv
await self._on_disconnect()
File …
```

FIX: Avoid race between client unsubscribe and circuit disconnect.

---

caproto/_broadcaster.py

Like circuits, broadcaster should DEBUG logs commands parsed, not just bytes received.

MNT: Broadcaster should log like circuit does.

---

caproto/server/common.py

First caproto PR 🎉 
This should be fairly simple, but I am pretty unfamiliar with this stuff so please correct me.
1. `metadata` is a reference so I do not want to mutate that information so it looked like I was forced to create a new `metadata` object.
2. Am I guaranteed to get a `DBR_TIME_LONG` or do I need to introspect the class and create a new one that way?
```
(caproto) [trendahl@psbuild-rhel7-02  caproto]$ caget -a simple:A
simple:A                       2018-06-12 13:17:21.927088 1  
(caproto) [trendahl@psbuild-rhel7-02  caproto]$ caget -a 'simple:A.{"ts": {}}'
simple:A.{"ts": {}}            2018-06-12 13:33:48.677312 1  
```

ENH: Channel Access timestamp filter

---

caproto/threading/client.py

Demo that threads clean up on exit:
```py
>>> from caproto.threading.client import Context
>>> with Context() as ctx:
...     pv, = ctx.get_pvs('simple:A')
...     print(pv.read())
... ReadNotifyResponse(data=array([1], dtype=int32),
data_type=<ChannelType.LONG: 5>, data_count=1,
status=CAStatusCode(name='ECA_NORMAL', code=0, code_with_severity=1,
severity=<CASeverity.SUCCESS: 1>, success=1, defunct=False,
description='Normal successful completion'), ioid=1, metadata=None)
>>> import threading
>>> threading.active_count() 1
```
Closes #281

ENH/FIX: Implement context magic methods on Context.

---

caproto/sync/client.py
caproto/tests/test_threading_client.py
caproto/threading/client.py

The sync client already does this. (Checked interactively.)
This PR makes the threading client do the same and adds a test.

ENH: Accept scalar or str/bytes in write.

---

caproto/curio/client.py
caproto/server/common.py
caproto/sync/client.py
caproto/sync/repeater.py
caproto/tests/test_core.py
caproto/tests/test_nonet.py
caproto/tests/test_serialization.py
caproto/threading/client.py
caproto/trio/client.py

Closes #302
``version=13`` has been scrubbed from the code and tests. It still
appears in some docs example, which I think is good/fine.

REF: Replace version=13 with version=ca.DEFAULT_PROTOCOL_VERSION.

---

caproto/_data.py
caproto/_utils.py
caproto/ioc_examples/states.py
caproto/server/common.py
caproto/server/records.py
caproto/server/server.py
caproto/tests/conftest.py
caproto/tests/test_channel_filters.py
caproto/tests/test_threading_client.py

States are defined on the `PVGroup` level, inherited from the parent if not specified. Currently set in the class definition, but this probably should be redone - looking for suggestions.
~Note: No short-hand syntax support just yet~
Adds simple `PvProperty` for boolean values with ['No', 'Yes'] as the enum strings.
Closes #267 
Closes #300

ENH: add full support for the sync filter

---

caproto/threading/client.py
doc/source/release-notes.rst

The original motivation for having one threadpool per context (and by default one worker in that threadpool) was to ensure that updates were processed in order.
This was overkill: the server itself can only guarantee ordering within a circuit; it does not coordinate *between* circuits in a context. Therefore it is safe to use one worker per circuit. This PR implements this as one threadpool per circuit, with the number of workers in the threadpool defaulting to one but configurable by the user.

ENH: Expose number of workers per circuit as an argument to Context

---

caproto/commandline/monitor.py
caproto/ioc_examples/mini_beamline.py
caproto/server/server.py

Addresses #324 
A simple enhancement without requiring further modification of `PVSpec`.
Added microseconds in `caproto-monitor` output so you can see current updating; example with timedelta in the expandable section below. Upsides/downsides follow.
<details>
```
$ caproto-monitor mini:current --format "{timedelta} {response.data}"
0:00:00.006681 [ 482.31322727]
0:00:00.100726 [ 479.75035273]
0:00:00.100883 [ 477.69062017]
0:00:00.100941 [ 476.18900918]
0:00:00.100933 [ 475.28488873]
0:00:00.100950 [ 475.00069802]
0:00:00.100884 [ 475.34340477]
0:00:00.100908 [ 476.30423468]
0:00:00.100922 [ 477.85958347]
0:00:00.100883 [ 479.96916718]
0:00:00.100905 [ 482.58100906]
0:00:00.100950 [ 485.63166917]
0:00:00.100878 [ 489.03979987]
0:00:00.100914 [ 492.72308764]
0:00:00.100854 [ 496.58860719] …
```

ENH: pvproperty scan

---

caproto/threading/client.py
caproto/threading/pyepics_compat.py
doc/source/release-notes.rst

This prompts the question, should we change the API of the access_rights_callback
to be the same --- to take the PV instance as the first argument? I think that
we should.

DOC: Correct inaccurate docstring.

---

caproto/asyncio/server.py

Caught this problem when I saw this error go by in a server log:
```
[E 14:52:04.290 server:237] Server error. Will shut down
File "/usr/lib/python3.6/asyncio/selector_events.py", line 1102, in sendto
self._sock.sendto(data, addr)
OSError: [Errno 101] Network is unreachable
During handling of the above exception, another exception occurred:
File "/home/dallan/Repos/bnl/caproto/caproto/asyncio/server.py", line 223, in run
await asyncio.gather(*tasks)
File "/home/dallan/Repos/bnl/caproto/caproto/server/common.py", line 536, in broadcast_beacon_loop
File "/home/dallan/Repos/bnl/caproto/caproto/asyncio/server.py", line 180, in send
self.transport.sendto(bytes_to_send, self.address)
File …
```

FIX: Implement error_received method of asyncio.Protocol interface.

---

caproto/commandline/get.py
caproto/commandline/monitor.py
caproto/commandline/put.py
caproto/commandline/repeater.py

I remember someone (@tacaswell) remarking that it is annoying that ``-vvvv`` is
less verbose than ``-vvv``, and it's easy enought to make ``-v`` a "count"
thing rather than a "store_true" thing. This is also exactly how ansible's
verbosity CLI flag is handled, as a point of precedent.

ENH: In CLIs, accept -vvvvvvvv(etc) as a synonym for -vvv.

---

caproto/commandline/put.py

Not noticed because the CI is in a sorry test. Verified locally that
test_cli_scripts.py is happy now.

HOTFIX: Typo in cf91c154 broke caproto-put.

---

caproto/server/common.py
caproto/tests/test_channel_filters.py

It was comparing network-endian arrays rather than host-endian.

FIX: Deadband filter now works without numpy.

---

caproto/tests/test_threading_client.py

Example of a false failure that this is meant to address:
```
_______________________ test_specified_port[epics-base] ________________________
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fa311bc7f28>
context = <Context searches_pending=1 circuits=0 pvs=1 idle=0>
ioc = namespace(name='Waveform and standard record IOC', prefix='e9a34ecc:', process=<subprocess.Popen object at 0x7fa30e79a...m', 'str': 'e9a34ecc:str', 'int': 'e9a34ecc:int', 'int2': 'e9a34ecc:int2', 'int3': 'e9a34ecc:int3'}, type='epics-base')
def test_specified_port(monkeypatch, context, ioc):
pv, = context.get_pvs(ioc.pvs['float'])
>       pv.wait_for_connection()
caproto/tests/test_threading_client.py:89: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
<snip>
caproto/threading/client.py:92: TimeoutError
``` …

TST: Use very generous timeouts in threading tests.

---

caproto/_array_backend.py
caproto/_backend.py
caproto/_circuit.py
caproto/_data.py
caproto/_numpy_backend.py
caproto/_utils.py
caproto/sync/client.py
caproto/tests/epics_test_utils.py
caproto/tests/test_data_conversion.py
caproto/tests/test_server.py
caproto/threading/client.py

Initial commit does some minor cleaning of conversion code, fixes testing on byte arrays.
Hopefully a bit more clear?
2nd commit is up for consideration. I think we need to centralize _all_ conversion functions. First thought was to move them to `caproto._backend` to start with. I could easily be convinced to do it a different way, though...

CLN: initial attempt at cleaning conversions

---

caproto/_commands.py
caproto/_constants.py
caproto/asyncio/server.py
caproto/commandline/get.py
caproto/commandline/monitor.py
caproto/commandline/put.py
caproto/curio/server.py
caproto/ioc_examples/random_walk.py
caproto/server/common.py
caproto/server/server.py
caproto/tests/test_threading_client.py
caproto/threading/client.py
caproto/trio/server.py
doc/source/protocol-compliance.rst
doc/source/release-notes.rst
doc/source/threading-client.rst

Tested interactively, it correctly starts dropping updates for a specific Subscription on the floor if a given client is behind.
If there is a backlog of EventAddResponses to send, it starts batching them into blocks to send at once. This is tested interactively too and seems to work well.

FIX: Enforce quotas per subscription under high load.

---

doc/source/install.rst

Forgot to push this with the previous PR, oops...

DOC: point to location of iOS example IOCs

---

.flake8
caproto/_constants.py
caproto/_data.py
caproto/asyncio/server.py
caproto/ioc_examples/caproto_to_ophyd.py
caproto/ioc_examples/rpc_function.py
caproto/server/common.py
caproto/server/conversion.py
caproto/server/server.py
caproto/sync/repeater.py
caproto/tests/_asv_shim.py
caproto/tests/test_threading_client.py
caproto/threading/client.py
caproto/threading/pyepics_compat.py
generate_headers.py

TODO: consider determining MTU per interface dynamically in the future.
There may not be portable solutions for this.
Linux: https://gist.github.com/nzjrs/8934855
(Seen on ophyd areadetector testing on OSX - part of an upcoming PR)
Edit: 
(1) a bit of pork in 232a169, pyepics compat in threading client was calling the incorrect connection state changed method, meaning that `epics.PV` connection callbacks were never run.
(2) new flake8 is much more strict

FIX: use by default minimum MTU likely to be seen in the wild

---

caproto/_circuit.py
caproto/_data.py
caproto/_utils.py
caproto/server/common.py
caproto/server/server.py
caproto/sync/client.py
caproto/threading/client.py
caproto/threading/pyepics_compat.py

The current DEBUG logs do not include PV names except at channel
creation time. This adds DEBUG logs to channel-level logging that
include the PV name, read request/response, write request/response, and
event response. It omits event request because that is managed
asynchrously by the circuit and is typically of lower operational
interest.

ENH: More debug prints in threading client.

---

caproto/_utils.py
caproto/asyncio/server.py
caproto/curio/client.py
caproto/server/common.py
caproto/sync/client.py
caproto/sync/repeater.py
caproto/threading/client.py
caproto/trio/client.py

Should improve this kind of scenario by chaining the OSError with a
CaprotoNetworkError that includes the address we attempted to connect
to.
```
$ caproto-get simple:A -vvv
[D 11:47:43.096 repeater:213] Another repeater is already running; will not spawn one.
[D 11:47:43.097 client:52] Registering with the Channel Access repeater.
[D 11:47:43.097 _broadcaster:72] Serializing 1 commands into one datagram
[D 11:47:43.097 _broadcaster:75] 1 of 1 RepeaterRegisterRequest(client_address='0.0.0.0')
File "/Users/mrakitin/anaconda3/envs/bluesky/bin/caproto-get", line 11, in <module>
load_entry_point('caproto', 'console_scripts', 'caproto-get')()
File "/Users/mrakitin/anaconda3/envs/bluesky/lib/python3.6/site-packages/caproto/commandline/get.py", line 102, in …
```

ENH: Show better error msg with addr if sendto fails.

---

caproto/threading/client.py

This appears to be causing deadlock while using connection callbacks in ophyd.

FIX: connected property should not acquire lock

---

caproto/_broadcaster.py
caproto/_state.py
caproto/tests/test_threading_client.py
caproto/threading/client.py

Based on what I've seen locally with barrier breakage using 100 to 300+ threads, it seems that the time needed to complete these tests on travis is significantly greater than when run locally. Let's see if this makes multithreaded tests pass more repeatably.

TST: increase barrier wait time due to travis slowness

---

.editorconfig

This should tell vim/emacs/whatever to line-wrap at 79. Notice that
we only _enforce_ wrapping at 115 to allow for the occasional situation
where a longer line is easier to read. But we encourage wrapping at 79.

Add an editorconfig.

---

caproto/threading/client.py

Example usage:
```
In [1]: from caproto.threading.client import Context
In [2]: ctx = Context()
In [3]: pv, = ctx.get_pvs('rpi:color')
In [4]: pv.access_rights
Out[4]: <AccessRights.WRITE|READ: 3>
```
for @hhslepicka

ENH: Stash latest AccessRights as state on PV.

---

caproto/tests/conftest.py

Simple tweak - allow toggling of `-vvv` for example IOCs.
This utility function is now used in ophyd as well, so it's nice to have some additional control over the output.

TST: allow toggling very-verbose -vvv when running example IOCs

---

caproto/_data.py
caproto/sync/client.py

This prevents subscriptions for being processed for all signal that
share an alarm if the alarm state has not actually changed.

FIX: only propose changing the alarm state if it is actually changed

---

caproto/_utils.py
caproto/asyncio/server.py
caproto/tests/test_utils.py

1. netifaces should not have been used here.
2. asyncio server had some custom code where it could have just used the provided `create_datagram_endpoint` kwargs
API: removes internal function `broadcast_address_list_from_interfaces`
Closes #398

FIX: broadcast addresses

---

caproto/threading/pyepics_compat.py

Additional IOC for debugging alarm-related events (`DBE_ALARM`) - not yet used in this PR.
I think caproto servers may send events despite clients not requesting them (TODO add test cases and chat with @danielballan )
Closes #396

FIX: pyepics_compat default sub mask

---

caproto/_log.py
caproto/commandline/get.py
caproto/commandline/monitor.py
caproto/commandline/put.py
caproto/commandline/repeater.py
doc/source/loggers.rst

We copied the caproto logging utilities to bluesky and improved on it there,
thanks mostly to input from @mrakitin. This PR copies those improvement back
to caproto.

API: Deprecate color_logs in favor of set_handler.

---

caproto/threading/client.py
doc/source/loggers.rst

This refines the work in #370 to ensure that _all_ read/write requests and responses, including those with `wait=False` and those initiated via a batched request, generate DEBUG messages in the coresponding PV/channel logger.

DEBUG-log read/write request and responses always

---

caproto/asyncio/server.py
caproto/curio/server.py
caproto/examples/trio_client_simple.py
caproto/server/common.py
caproto/tests/test_examples.py
caproto/trio/client.py
caproto/trio/server.py
caproto/trio/util.py
setup.py
test-requirements.txt

This PR looks more drastic than it is. It effectively breaks up the "common" server loops into 2 methods - splitting queue access and parse/respond:
1. `*_loop()` Reference loop implementation, functioning just like current master's loops - grabbing from a queue and calling `*_iteration()` (2)
2. `*_iteration()` "Single iteration" - the portion which takes a single command and does something with it
I think I prefer this compared to the current implementation regardless of the trio memory channel refactor.
Addresses #357

REF: replace (deprecated) trio queues with trio memory channels

---

caproto/threading/client.py

It's only a problem if we see the same search result from different servers.
We should not warn about seeing two results from the same server.

FIX: Do not warn if the same result arrives twice

---

caproto/_data.py

New flake8 versions find over-indented method blocks now, apparently. 
Discovered in #436 travis results; blame indicates this has been there for a few months.

STY: flake8 found an over-indented method block

---

.travis.yml
azure-pipelines.yml
azure_env.sh
caproto/tests/test_pyepics_compat.py
setup_local_dev_env.sh

* R3-14 now in azure test matrix, along with R7 (3.6, 3.7)
* epics-on-travis is updated to 0.8.2 with some miscellaneous fixes and clean-ups
* `versions.sh` now provided with epics-on-travis individual releases, significantly cleaning up test matrix environment variables
Notes
------
* `setup_local_dev_env.sh` should be revisited at some point
* R3-15, R3-16 could easily be added to azure if desirable

CI: add R3-14 to the azure test matrix; bring travis/azure up to epics-on-travis 0.8.2

---

caproto/tests/test_threading_client.py

These iterations are to expose a subtle race condition in the
threaded client, however they are not useful for actually debugging it
anymore and my repeating them we are pushing up the odds that at least
on run on CI fails erroneously.

TST: turn down iterations

---

caproto/tests/test_threading_client.py
caproto/threading/client.py
doc/source/threading-client.rst

@brunoseivam's post over in pyepics got me thinking about how to reuse
the beacon and echo information we are already collecting to expose a
"healthcheck" feature in caproto.
This is what it looks like when we are checking in on one healthy server and
one server that has died since we first connected to it.
```python
In [2]: from caproto.threading.client import Context
In [3]: ctx = Context()
In [4]: pvs = ctx.get_pvs('rpi:color', 'random_walk:x', 'random_walk:dt')
<some time later>
In [34]: ctx.broadcaster.time_since_last_heard()
Out[34]: 
{('192.168.86.245', 50421): 31.009815337019973,
('192.168.86.21', 5064): 27.976911116042174}
In [35]: ctx.broadcaster.time_since_last_heard()
Out[35]: 
{('192.168.86.245', 50421): 1.173450144007802,  # <-- This server just sent a beacon …
```

ENH: Add time_since_last_heard to Broadcaster.

---

caproto/_circuit.py
caproto/_commands.py
caproto/_data.py
caproto/curio/client.py
caproto/ioc_examples/type_varieties.py
caproto/tests/conftest.py
caproto/tests/epics_test_utils.py
caproto/tests/test_serialization.py
caproto/tests/test_server.py
caproto/tests/test_threading_client.py
caproto/trio/client.py

Empty arrays (primarily those of type char/string) behaved strangely with `caget`, sometimes spouting:
`*** CA error: invalid element count requested`
This appears to be due to `max_length` assumptions in `ChannelData` when the initial value is empty (empty string, empty list/array).
State before and after this PR's changes:
* Master: Unless specified otherwise, that the maximum length of data `ChannelData` will hold is the length of the initial value
* PR: If initial value is empty, assume scalar and set max_length=1.
Closes #399 (for now)

FIX: strings invalid element count requested; max-length assumptions for unspecified values

---

caproto/sync/shark.py

This was caught when trying to use caproto-shark at the SIX beamline. The
symptom was:
```py
File "/opt/conda_envs/collection-2019-1.0-six/lib/python3.6/site-packages/caproto/sync/shark.py", line 234, in infer_command_class
return one_way_commands[id_]
KeyError: 0
During handling of the above exception, another exception occurred:
File "/opt/conda_envs/collection-2019-1.0-six/bin/caproto-shark", line 11, in <module>
sys.exit(main())
File "/opt/conda_envs/collection-2019-1.0-six/lib/python3.6/site-packages/caproto/commandline/shark.py", line 39, in main
for namespace in shark(sys.stdin.buffer):
File "/opt/conda_envs/collection-2019-1.0-six/lib/python3.6/site-packages/caproto/sync/shark.py", line 279, in shark
data, …
```

FIX: Always raise ValidationError when deserialization fails.

---

caproto/_utils.py
caproto/tests/test_utils.py

Thanks to @mrakitin for perservering to get to the bottom of this and
thanks to ZY (not sure of his GitHub handle) for some assistance.
This _partially_ reverts #404. I believe the changes to the server in
#404 are correct but the changes to the client were not correct.
When `EPICS_CA_AUTO_ADDR_LIST='yes'`, clients should search on the
broadcast address of each interface rather than only
`['255.255.255.255]`.
See https://github.com/epics-base/epics-base/blob/d77a96d23d962f996f12e29255aa29beed64c1b1/modules/ca/src/client/iocinf.cpp#L223
@mrakitin will post a follow-up comment shortly showing that this
fix works in production.
This does raise a question for me about whether we should add
``netifaces`` as a required dependency for caproto (heresy!). Silently
falling back to …

FIX: Client should use broadcast addresses.

---

caproto/commandline/cli_print_formats.py
caproto/commandline/get.py
caproto/commandline/monitor.py
caproto/tests/test_cli_scripts.py

The proposed feature implements support for CLI arguments specifying output formatting for `caproto-get`:
- **floating point formats**: `-e -f -g -s -lx -lo -lb` 
- **integer numbers**: `-0x -0o -0b`
The arguments change output formatting whenever floating point or integer values are printed to `stdout`. If a format string is specified in the argument list (e.g. `--format="{pv_name} {response.data}"`), the changed formatting is applied to the field `{response.data}`. If the field specification differs (e.g. `{response.data[0]}`) then the default format or format supplied within `--format` string is used. For example, the argument sequence `-0b --format="{response.data[0]:X}"` will print integer as hex number, despite `-0b` argument that selects binary format. The formatting also works in …

Support for CLI output formatting arguments in 'get.py'

---

caproto/benchmarking/util.py

Looking at this, the "benchmarking" module we're using to spawn all of our test IOCs could use _some_ cleaning.

MNT: remove deprecated StopIteration for softioc context manager

---

doc/source/iocs.rst

Just fixed a small typo I noticed in the IOC documentation.

Typo fixed in IOC docs

---

caproto/commandline/cli_print_formats.py
caproto/commandline/get.py
caproto/commandline/monitor.py
doc/source/command-line-client.rst

This is the followup on my previous pull request:
1. A new doc section on the new CLI formatting options. File `doc/source/command-line-client.rst`.
2. I noticed that addition of option `-d` to the mutually exclusive group with `--terse`, `--wide` and `--format` broke some advanced functionality of `caproto-get`, which requires simultaneous use of -d and --format options (for example `$ caproto-get random_walk:dt -d control --format="{response.metadata}"` is not working). After consideration, I would propose to remove option `--format` from the group instead of removing `-d`. If `--format` is used with `--wide` or `--terse`, then the default formatting is overridden with the specified format string. This behavior seems more intuitive for the user compared to simultaneous use of `-d` and …

Docs on the new CLI parameters, fix for caproto-get

---

caproto/ioc_examples/mini_beamline.py

At the NSLS-II User Meeting'19 participants of the [Bluesky tutorial](https://usersmeeting.ps.bnl.gov/workshops/workshop.aspx?year=2019&id=160) complained about the integer positions in the scan reported by the [`motor_ph`](https://github.com/bluesky/tutorial/blob/f3442674f0ee381c4e9fe23756d15604b83b574d/scripts/beamline_configuration.py#L155-L156) motor. The precision for that motor is set to `0`:
This PR attempts to resolve it.

ENH: add precision to motor_ph in mini_beamline

---

caproto/ioc_examples/scalars_and_arrays.py

This was sitting in a stash on my laptop, I think this will make the
example IOC play nicer with viewers.

MNT: make enum field on scalars_and_arrays mock a bi record

---

caproto/_utils.py

Attempt to fix a bug reported on the Nikea Slack where `filter_` is `None`:
```python
modifiers = parse_record_field(name).modifiers
if modifiers is not None:
self.channel_filter = parse_channel_filter(modifiers.filter_)
```

FIX: Handle case where filter_ is None or empty.

---

caproto/sync/client.py

`caproto-get` fails confusingly with the following without this fix:
```
$ caproto-get VMTEST:m1
an integer is required (got type str)
```
There may be other cases where we aren't changing these to `int()`...

FIX: EPICS_CA_REPEATER_PORT needs to be an integer

---

.travis.yml

Correction to #479. Once it was merged and tried to publish the docs, we can
see that [it failed](https://travis-ci.org/caproto/caproto/jobs/530885729)
becauasethe token was (correctly) set up for caproto.github.io
but the command to push tries (incorrectly) to publish to bluesky.github.io.

CI: Fix typo in doctr deploy command.

---

caproto/commandline/put.py

Previously there was no way to do something like:
```
caproto-put rpi:color 000000
```
where ``000000`` is a string. Now, we can do
```
caproto-put -S rpi:color 000000
```
and it works as intended.

Add support for caproto-put -S.

---

caproto/ioc_examples/worker_thread.py
caproto/tests/test_examples.py

For @johnsinsheimer
Comments from others welcome -- there may be a smarter way to do this that I haven't thought of.
This IOC starts a worker thread at startup. When a client puts to the `wt:request` PV, the IOC sends a task the worker. When the worker completes the task, it notifies the IOC, and the IOC updates the `wt:response` PV, triggering any monitors to update.
In this toy example, the "request" to the worker is some number of seconds to sleep for, and the "response" is an incremented counter. Demo:
Client side:
```
09:39 $ caproto-put wt:request 3
Old : wt:request                                [0]
New : wt:request                                [3]
09:40 $ caproto-monitor wt:response
wt:response                               2019-08-30 09:40:53.370741 [0]
wt:response …
```

Add example with IOC that does work on a thread.

---

CONTRIBUTING.md
doc/source/command-line-client.rst
doc/source/install.rst
doc/source/iocs.rst
doc/source/protocol-compliance.rst
doc/source/release-notes.rst

Found all the remaining carryovers of `NSLS-II` in the codebase using `grep`.

Scrub more NSLS-II -> caproto.

---

caproto/asyncio/server.py
caproto/curio/server.py
caproto/ioc_examples/worker_thread_pc.py
caproto/tests/test_examples.py
caproto/trio/server.py

This is a follow-up to #508.
In #508, the ``wt:request`` is "complete" as soon as the request is sent to
the worker. Per past conversations with Andrew Johnson and others, the *proper*
behavior is for writes to "complete" when *all actions* resulting from that
write are done. Thus, the correct implementation of put-completion would be
for ``wt:request`` to "complete" the worker thread finishes processing the
request.
In this example, ``caproto-put ...`` waits for put-completion while the worker
processes the request to sleep.
```
$ caproto-put --timeout 10 --notify wt:request 3
Old : wt:request                                [0]
New : wt:request                                [3]
```
This makes this easier on the downstream (e.g. ophyd) side because you don't
need to coordinate between …

Add a worker thread example with put-completion.

---

doc/source/release-notes.rst

Let's get a release out to make ``async_lib.Event`` available so that the new 
``worker_thread_pc`` IOC example works on a released version of caproto.

Release notes for v0.4.1

---

doc/source/clients.rst
doc/source/index.rst

Put all the clients' documentation under a landing page that gives an overview.
This important context is currently scattered across each client's respective
documentation page. It would be good to have it all together here.
Closes #517
Language adapted from @klauer's comment in that issue.

Put clients under a section with some context.

---

caproto/_data.py
caproto/ioc_examples/enums.py
caproto/server/records.py
caproto/tests/test_examples.py

Specify an enum in a `pvproperty`, and `ZNAM` and `ONAM` for mocked `bi`/`bo` records will be automatically linked.
Example IOC + test added.

ENH: link ZNAM and ONAM to the parent enum_strings

---

caproto/threading/client.py

This is based on the discussion in the [Nikea Slack](https://nikea.slack.com/archives/C7QGYD0KW/p1568722811013200). The proposed update allows setting a global timeout via an environment variable `CAPROTO_TIMEOUT`.

Allow setting a global timeout via CAPROTO_TIMEOUT env var

---

caproto/tests/conftest.py

We seem to hit the trio servers before they are ready.

TST: be more forgiving while trying to start the test server

---

caproto/ioc_examples/mocking_records.py
caproto/server/records.py
caproto/server/server.py
caproto/tests/test_records.py

Something like this:
```python
heartbeat = pvproperty(value=0, mock_record='bo', doc='The heartbeat signal')
```
Becomes:
```bash
$ caget -S heartbeat.RTYP
heartbeat.RTYP bo
$ caget -S heartbeat.DESC         # <----
heartbeat.DESC The heartbeat signal
```

ENH: pvproperty doc kwarg becomes DESC

---

caproto/asyncio/server.py
caproto/curio/server.py
caproto/ioc_examples/big_image_noisy_neighbor.py
caproto/server/common.py
caproto/tests/test_examples.py
caproto/trio/server.py

This fixes a bug when:
- there is a ReadResponse that `sock_sendall` can not send in on go
- there is a monitor that will fire during that readout
Because the buffer for the ReadResponse is sent in parts, the bytes
for the AddEvent can get sent while the client still thinks it is
receiving the payload from the ReadResponse.  The tail of the payload
will then be read as the next message from the server.
a) corrupt the read payload
b) result is a bogus message
---
A minimal example to reproduce the problem is
server:
```python
#!/usr/bin/env python3
import time
from caproto.server import pvproperty, PVGroup, ioc_arg_parser, run
import numpy as np
image_shape = (3960, 3960)
class IOInterruptIOC(PVGroup):
t1 = pvproperty(value=2.0)
dt1 = pvproperty(value=0.9, dtype=float, precision=3)
image = …
```

FIX: add a lock to sending over a VirtualCircuit

---

.travis.yml
caproto/tests/conftest.py

This makes the fixtures and utility functions usable without trio or
curio installed.

Hide experimental deps in fixtures.

---

.gitignore
caproto/_broadcaster.py
caproto/_circuit.py
caproto/_commands.py
caproto/_dbr.py
caproto/_log.py
caproto/asyncio/server.py
caproto/curio/client.py
caproto/curio/server.py
caproto/ioc_examples/dynamic_pvgroups.py
caproto/server/__init__.py
caproto/server/common.py
caproto/server/conversion.py
caproto/sync/client.py
caproto/tests/conftest.py
caproto/tests/test_core.py
caproto/tests/test_examples.py
caproto/tests/test_server.py
caproto/tests/test_threading_client.py
caproto/tests/test_utils.py
caproto/threading/client.py
caproto/threading/pyepics_compat.py
caproto/trio/client.py
caproto/trio/server.py
doc/source/clients.rst
doc/source/index.rst

This PR does a bunch of stuff, most notably.
* Correctly deal with the fact that a UDP socket does not always have one
address, sometimes broadcasts to many.
* Avoid logging some sent messages at both the circuit level and the channel level,
which produced redundant output.
* Adds more structured info to the LogRecord (bytesize, and counter for multi-command
datagrams)
* Fixes some display inconsistencies.
* Generally tightens up the lines based on some working experience trying to
use this in practice.
There is also a bunch of flake8 cleanup to respect new flake8 rules, most of
which I found constructive and caught at least one minor bug. All of that noise
is contained in one commit.

WIP: Polish logging.

---

caproto/tests/test_threading_client.py
caproto/threading/client.py
caproto/threading/pyepics_compat.py
doc/source/release-notes.rst
doc/source/threading-client.rst

In #545, @vstadnytskyi pointed out that it is inconvenient that subscription
updates do not carry information about which PV they pertain to. @tacaswell
suggested that we could change the signature of user callbacks to include the
PV as well as the raw response. Getting even more specific, we can include
the Subscription object `sub`, from which you can access the PV as `sub.pv` and the PV
name as `sub.pv.name`. That is, the callback signature would change from
``f(response)`` to ``f(response, sub)``.
(An alternative proposal, adding the PV name to the response, was rejected
because we have held that Message objects contain nothing more or less
than the information sent over the wire.)
Fortunately, this change can be made in a backward-compatible way. When a
user callback is first …

Provide Subscription to user callback.

---

caproto/_utils.py
caproto/asyncio/server.py
caproto/curio/client.py
caproto/curio/server.py
caproto/server/common.py
caproto/sync/client.py
caproto/tests/test_threading_client.py
caproto/threading/client.py
caproto/trio/client.py
caproto/trio/server.py

Our discussion around how to fix #514 has led to some clarity but also some open questions. I think it's fair to say that no one involved in the discussion so far is feeling confident that we understand the implications deeply enough to prescribe the single correct way forward. Rather than picking one, I suggest we apply this targeted workaround to the specific issue that broke caproto on Windows in v0.4.0. The discussion can continue, perhaps pulling in new expertise, and we can go from there, hopefully eventually retiring this workaround.
If there are no strong objections, I would like to merge this and release a working 0.4.x release this week.

Direct fix for #514

---

doc/source/release-notes.rst

Will merge by end of day. The breaking change Python made to to 3.6.10, 3.7.6, and 3.8.1---noted in the release notes---has made this an urgent release on all platforms.

Add release notes for v0.4.3.

---

caproto/sync/client.py
doc/source/sync-client.rst
doc/source/threading-client.rst

In the narrative docs we don't mention how to read timestamps in the sync or
threading clients. There is just an oblique reference in the `read`'s
docstring. There is also no mention anywhere of the `to_datetime()` convenience
method, which I had actually forgotten about and would probably be quite useful.

Document `data_type` more prominently.

---

test-requirements.txt

It looks like a recent curio release broke us.
Pin it down until we have the resources to investigate.

Pin curio down to <1.0.

---

caproto/server/common.py
caproto/tests/_asv_shim.py

Newer versions of pytest are strict about unregistered marks.

MNT: tweak pytest, fix import deprecation

---

caproto/asyncio/server.py
caproto/tests/test_examples.py

See https://bugs.python.org/issue37228  This is the workaround
suggested in the issue.
This only needs to be in the asyncio code because the change that is
causing problems is to `create_data_endpoint` not to Python's socket
support in general.
I think this will fix many of the test failures we are seeing due to test servers not starting.

FIX: explicitly use SO_REUSEADDR

---

caproto/_data.py
caproto/server/menus.py
caproto/server/records.py
caproto/tests/test_core.py
caproto/tests/test_examples.py

There are limits to both the length of the enum strings and the number
of enum
entries (https://github.com/epics-base/epics-base/blob/d0c4cc0cec8d31b88ee480d2d7f007f17cf0cdbf/modules/ca/src/client/db_access.h#L38-L40)
which we do have encoded in `_constants.py` and respect on sending the
value out, but we should reject invalid values being sent on the way in.

FIX: validate enum strings

---

caproto/sync/client.py
caproto/tests/conftest.py
caproto/tests/test_cli_scripts.py

Closes #564.
In Python3, checking if a variable `isinstance` of `str` should be sufficient to determine stringyness.
The previous condition prevented enum type PVs from being set.

Check if data is of type str

---

caproto/_utils.py
caproto/commandline/monitor.py
caproto/sync/client.py
caproto/threading/client.py
doc/source/sync-client.rst

In #574 we changed the expected signature for user subscription callbacks from
`f(response)` to `f(sub, response)` in the threading client. This PR
applies the same changes to the sync client, and it updates `caproto-monitor`
accordingly.
I went to apply the same change to the async clients (trio, curio) and found
that they are too far behind for this to be applicable. We still haven't
separate the "create subscription object" and "add callback" steps there.
I think we should wait to worry about that until we unify the clients around
a shared utility module, as we have done for the servers.
So, this PR completes the subscriptions refactor and paves the way for 0.5.0.

Provide Subscription to user callback (in sync client).

---

caproto/_backend.py
caproto/_data.py
caproto/_dbr.py
caproto/_utils.py
caproto/ioc_examples/mocking_records.py
caproto/server/common.py
caproto/server/server.py
caproto/tests/test_data_conversion.py
caproto/tests/test_examples.py

This is at least working locally - I _believe_ correctly:
```
$ cainfo mock:E.VAL
mock:E.VAL
State:            connected
Host:             192.168.99.1:5064
Access:           read, write
Native data type: DBF_STRING
Request type:     DBR_STRING
Element count:    1
$ cainfo mock:E.VAL$
mock:E.VAL$
State:            connected
Host:             192.168.99.1:5064
Access:           read, write
Native data type: DBF_CHAR
Request type:     DBR_CHAR
Element count:    14
$ caget -S mock:E.RTYP
mock:E.RTYP stringin
$ caget -S mock:E.RTYP$
mock:E.RTYP$ stringin
$ caget -S mock:E.VAL$
mock:E.VAL$ this is a test
```
And not shown for other fields:
```
$ caget -S mock:C.RTYP
mock:C.RTYP ai
$ caget mock:C.VAL$
Channel connect timed out: 'mock:C.VAL$' not found.
```
cc @baldwinb (please chime in if I'm …

FIX: Long string modifier ('PV$') for STRING/CHAR dtypes

---

caproto/threading/client.py

FIX: empty select() list is also problematic on OSX with KqueueSelector

---

caproto/threading/client.py

This uses selector API I overlooked to simplify the lookup of `ready socket -> ready object`.

REF: Use selector data to reduce threading client selector lookups

---

caproto/tests/conftest.py

While technically syntactically valid ('stuff''' -> 'stuff' + '')
it confuses the code-highlighter in emacs.

MNT: remove implicitly concatenated empty string

---

.gitignore
caproto/_utils.py
caproto/ioc_examples/mini_beamline.py
caproto/ioc_examples/records.py
caproto/server/conversion.py
caproto/server/server.py
caproto/tests/conftest.py
caproto/tests/epics_test_utils.py
caproto/tests/test_examples.py
caproto/tests/test_server.py
caproto/tests/test_threading_client.py
caproto/trio/server.py

The changes in this PR are addressing deprecated features of `trio`.
- `trio.run_sync_in_worker_thread` replaced by `trio.to_thread.run_sync`.
- `trio.BlockingTrioPortal()` followed by `portal.run(...)` or `portal.run_sync(...)` replaced by `trio.from_thread.run()` or `trio.from_thread.run_sync(...)`
- There is no straightforward fix for deprecated `trio.Event.clear()`. The class `Event` in  `caproto/trio/server.py` was expanded to emulate the original `trio.Event.clear()` method.
The PR is addressing issues https://github.com/caproto/caproto/issues/548, https://github.com/caproto/caproto/issues/505 and https://github.com/caproto/caproto/issues/504.

Deprecated features of `trio`

---

doc/source/release-notes.rst

I couldn't find the pyepics version being pinned anywhere, so I don't think this actually needs any changes for the new 3.4.2 tag.
Do we still want a new caproto release now, or hold off for some more changes?

Release notes for 0.5.1

---

caproto/server/server.py

Simple fix.
@danielballan @ke-zhang-rd do you have a recommendation as to best setting up logging with an IOC external to caproto? e.g., a package `my_ioc` has `MyPVGroup`, making for a logger name `my_ioc.MyPVGroup`.
I'm thinking I'd like to use the same handler to get the same record formatting and save to the same file (perhaps even tee to standard output as well). It doesn't seem to fit well into the current structure, but I may be missing something.

FIX: missing f-string in server log

---

caproto/_data.py

This PR adds a new option called 'with_callback' to `ChannelData.write()` that lets you choose whether to run the user-defined put method.

Add an option to perform a write without running the user's put method.

---

caproto/server/server.py
pytest.ini

Closes #620 
Partially addresses #619 
Note that from here, `pvgroup.prop_name` will return the `pvproperty` instance, whereas it used to return the `PVSpec` instance. I don't think there is any logic that relies on this nonsensical behavior, but it's not impossible.

REF: Allow access to pvproperty instances

---

caproto/ioc_examples/thread_client_monitor.py

~- Future: Create a generalized helper method to do this setup for you~
- Future: allow customization of PV to be mirrored (fixed at "simple:A" for now)
- Could be simplified if link status does not need to be replicated
Related https://github.com/caproto/caproto/issues/579 (does not close the issue)
cc @rajanplumley

ENH: add IOC example for monitoring and mirroring an external PV

---

caproto/_data.py
caproto/server/server.py
caproto/tests/ioc_process.py
caproto/tests/test_server.py
pytest.ini

Prerequisite PR #621
See attached example IOC, which will not work in the current master, as it errors with:
(1) Fixed by #621:
```
File "ioc_process.py", line 34, in <module>
ioc = ProcessIOC(**ioc_options)
File "/Users/klauer/docs/Repos/caproto/caproto/server/server.py", line 1224, in __init__
self._create_pvdb()
File "/Users/klauer/docs/Repos/caproto/caproto/server/server.py", line 1267, in _create_pvdb
pvprop.pvspec)
File "/Users/klauer/docs/Repos/caproto/caproto/server/server.py", line 1112, in channeldata_from_pvspec
**kw)
File "/Users/klauer/docs/Repos/caproto/caproto/server/server.py", line 111, in __init__
prop = new_dict[field]
KeyError: 'process_record'
```
And then 
(2) Fixed by this PR:
`$ caput process_test:record.PROC 1`
```
Invalid write …
```

FIX: .PROC (process_record) field putter

---

caproto/ioc_examples/autosave.py
caproto/server/autosave.py

Closes #546 
Usage
```python
At the top-level PVGroup, ensure only one AutosaveHelper SubGroup has been
added. Then, wrap any pvproperty to be saved with ``autosaved``:
::
autosave_helper = SubGroup(AutosaveHelper)
value = autosaved(pvproperty(1.0))
```
* Save period and filename can be modified in `YourPVGroup.__init__`.
* Saved in convenient JSON format (which is notably not compatible with the standard EPICS autosave tools)
* Fields can likewise be saved (by attribute name, at least for now) by specifying `autosaved(..., fields=['description', ...])`; description is done by default.
* Autosave-tagged pvproperties in subgroups will be found, so only the top-level AutosaveHelper is necessary.
* `PVSpec` is inflexible/immutable by design, so a small hack around that was necessary here. If …

ENH: add proof-of-concept autosave tools

---

caproto/ioc_examples/subgroups.py
caproto/server/server.py

TODO/refactor: `valid_init_kw` is copy/pasted in a few places here

ENH: allow init kwargs to pass through to SubGroups

---

doc/rebuild.sh
doc/source/conf.py

This is the result of my local rebuilding efforts to get doctr-versions-menu going.
I'm cautiously optimistic that new tags / master rebuilds won't break it, but we'll see.
Note: per-version docs are already available as a result of this. It's not required to merge this for that purpose.
https://caproto.github.io/caproto/master/
See the version selector on the bottom left:

DOC: bump copyright date, add rebuild script

---

setup.py

Do not force prototype, undesirable command-line tools on the user.
These can still be accessed by way of:
```
python -m caproto.pva.commandline.get
python -m caproto.pva.commandline.put
python -m caproto.pva.commandline.monitor
```
3.6 dataclasses backport simply does not work for us. Removed.
Goal before next release will be to remove new parsimonious requirement and get in some form of #643 to address address list issues.

MNT: remove pva command line tools for now

---

caproto/_utils.py
caproto/asyncio/client.py
caproto/curio/client.py
caproto/pva/sync/client.py
caproto/sync/client.py
caproto/tests/test_threading_client.py
caproto/tests/test_utils.py
caproto/threading/client.py
caproto/trio/client.py

* Leaves `ca.get_address_list` behind for (mostly) back-compat
* Adds `get_client_address_list`, which pairs well enough with `get_server_address_list` and `get_beacon_address_list` 
* Removes hard-coded ports in some places
Badly in need of double-checking. ~Will mark draft until I can find the time.~
~Logic in broadcasters particularly could use further refactoring, as we require the broadcaster instance to know which port it wants to send information on, rather than just saying `"send this to the address list with whatever the configured {repeater, ca server port} is"`~
Repeater registration with local address, removing `port` from `broadcaster.send(port)`.
Respecting ports by using `caproto.get_client_address_list`
Closes #645 
Closes #639

REF/FIX: use new `get_client_address_list`; do not use hard-coded ports

---

.pre-commit-config.yaml
caproto/commandline/cli_print_formats.py
caproto/commandline/get.py
caproto/commandline/monitor.py

I thought this worked before but frustratingly couldn't find a way to get an array of bytes to format a string.
With this PR, long strings are no problem:
```
$ caproto-get -s AT2L0:CALC:STATS:TraceDiffResults.VAL$
AT2L0:CALC:STATS:TraceDiffResults.VAL$    /Users/klauer/mc/envs/hxr-attenuator/lib/python3.7/tracemalloc.py:65: size=70.5 KiB (-70.5 KiB), count=902 (-902), average=80 B
```
Unclear if this will have any side effects - I don't really understand much of the CLI formatting code.

FIX: caproto-get/monitor char array

---

caproto/commandline/get.py
caproto/commandline/monitor.py
caproto/sync/client.py
caproto/tests/test_cli_scripts.py

A minor but long-standing thing: the last commandline argument that brings us
up to parity with `caget` and `camonitor`.
Closes #147

Add support for -# in caproto-get and -monitor.

---

.travis.yml

`dataclasses` definitely is not necessary; repeater is started twice; unclear about the others. Let's see what happens.

CI: cleanup

---

caproto/server/stats.py

Continuing building out the "caproto standard library" of sorts - things you'd expect to find on nearly every real EPICS IOC, like autosave. This adds some status information.
Capitalized PV names are standardized names, so I'd prefer to keep those.
Simply instantiate as subgroup:
```
from caproto.server import PVGroup, SubGroup
from caproto.server.stats import StatusHelper
class MyIOC(PVGroup):
stats = SubGroup(StatusHelper, prefix=':STATS:')
```
<details>
<summary>Example</summary>
```
PREFIX:STATS:ACCESS        Running
PREFIX:STATS:STARTTOD 2020-09-03 17:36:55.215026
PREFIX:STATS:TOD 2020-09-03 17:37:01.228745
PREFIX:STATS:HEARTBEAT     1
PREFIX:STATS:START_CNT     39
PREFIX:STATS:SYSRESET      0
PREFIX:STATS:RECORD_CNT    181
PREFIX:STATS:FD_MAX        256
PREFIX:STATS:FD_CNT        0 …
```

ENH: add IOC stats-like informational tool

---

caproto/benchmarking/util.py
caproto/tests/conftest.py
caproto/tests/dbd.py
caproto/tests/epics_test_utils.py
caproto/tests/test_pyepics_compat.py
caproto/tests/test_record_compliance.py
caproto/tests/test_repeater.py
caproto/tests/test_server.py
caproto/tests/test_shark.py

Make the tests more forgiving of missing dependencies.
Without pyepics or epics_base you can still test that caproto can talk to its self.  Early on I think we needed the safety blanket of always testing against the reference, but at this point I think we can, at least locally, bootstrap the testing.

Reduce the minimum requirements to run tests

---

caproto/ioc_examples/mirror.py

Example:
```
python -m caproto.ioc_examples.random_walk 
```
```
python -m caproto.ioc_examples.mirror --target random_walk:x
```
```
$ caproto-monitor mirror:value
mirror:value                              2020-09-23 22:07:38.115205 [1.47088]
mirror:value                              2020-09-23 22:07:41.115865 [2.14317]
mirror:value                              2020-09-23 22:07:44.117169 [2.14567]
```

Example: an IOC with an asyncio client.

---

.travis.yml

This PR fixed overwritten `index.html` in https://github.com/caproto/caproto.github.io. I'll leave it to @klauer to fix the file itself in the docs repo.
xref https://github.com/bluesky/hklpy/pull/39#issuecomment-700949731.

CI/DOC: do not update index.html in NSLS-II.github.io

---

caproto/ioc_examples/hardware_specific/barcode_reader.py
caproto/ioc_examples/mini_beamline.py
caproto/ioc_examples/pathological/defaultdict_server.py
caproto/ioc_examples/pathological/reading_counter.py
caproto/ioc_examples/pathological/spoof_beamline.py
caproto/ioc_examples/too_clever/areadetector_image.py
caproto/ioc_examples/too_clever/caproto_to_ophyd.py
caproto/ioc_examples/too_clever/caproto_to_typhon.py
caproto/ioc_examples/too_clever/dynamic_pvgroups.py
caproto/ioc_examples/too_clever/trigger_with_pc.py
caproto/tests/test_catvs.py
caproto/tests/test_doc_utils.py
caproto/tests/test_examples.py
caproto/tests/verify_with_catvs.py

Closes #616
The top-level directory contains only examples that are succinct and not overly
clever. The hope is too avoid bewildering new users by mixing straightforward
examples with pathological ones.
Summary of changes:
```
rename caproto/ioc_examples/{ => hardwarwe_specific}/barcode_reader.py (95%)
create mode 100644 caproto/ioc_examples/pathological/__init__.py
rename caproto/ioc_examples/{ => pathological}/defaultdict_server.py (99%)
rename caproto/ioc_examples/{ => pathological}/reading_counter.py (93%)
rename caproto/ioc_examples/{ => pathological}/spoof_beamline.py (97%)
create mode 100644 caproto/ioc_examples/too_clever/__init__.py
rename caproto/ioc_examples/{ => too_clever}/areadetector_image.py (99%)
rename caproto/ioc_examples/{ => too_clever}/caproto_to_ophyd.py (93%) …
```

Reorganize ioc_examples.

---

caproto/ioc_examples/shared_memory.py
caproto/ioc_examples/too_clever/shared_memory.py

Note
-----
This is Python 3.8 only due to the usage of https://docs.python.org/3/library/multiprocessing.shared_memory.html#module-multiprocessing.shared_memory
I have in the past made attempts with [`multiprocessing.SyncManager`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.managers.SyncManager) but have found it to be extremely slow when it comes to synchronization primitives.
Docstring / IOC description
----------
A multiprocessing.shared_memory.SharedMemory-backed IOC.
``image`` has a shape (``MAX_SIZE``, ) and is generated in a separate
process running :func:`image_generator`.
A :class:`multiprocessing.Pipe` notifies the main process that a new image
is available in a given shared memory slot, which has some associated
metadata in :class:`ImageSlot`.
This …

ENH: add multiprocessing SharedMemory example (Python 3.8+ only)

---

caproto/ioc_examples/gamepad.py
caproto/ioc_examples/hardware_specific/gamepad.py

```
caproto-monitor    gp:a    gp:b    gp:x    gp:y    gp:lb    gp:rb    gp:lx    gp:ly    gp:rx    gp:ry    gp:dx    gp:dy    gp:lt    gp:rt    gp:sel    gp:back    gp:alive gp:ld gp:rd
```
Attn @oksanagit
Yesterday Oksana and I were talking about an IOC for controlling
motors via a game pad.  This IOC gets as far as publishing the state
of the gamepad to EPICS.

ENH: add an example that publishes a gamepad input to the network

---

.pre-commit-config.yaml
caproto/pva/_circuit.py
caproto/pva/_data.py
caproto/pva/_dataclass.py
caproto/pva/_fields.py
caproto/pva/_messages.py
caproto/pva/_state.py
caproto/pva/_utils.py
caproto/pva/asyncio/server.py
caproto/pva/commandline/get.py
caproto/pva/commandline/monitor.py
caproto/pva/commandline/put.py
caproto/pva/ioc_examples/basic.py
caproto/pva/ioc_examples/group.py
caproto/pva/server/__init__.py
caproto/pva/server/commandline.py
caproto/pva/server/common.py
caproto/pva/server/magic.py
caproto/pva/sync/client.py
caproto/tests/test_pva.py
caproto/tests/test_pva_circuit.py
caproto/tests/test_pva_dataclass.py
caproto/tests/test_pva_server.py

I've been puzzling over how to handle serving dataclass information from the server in a not-so-terrible way for a long time.  
This PR is a first pass at that, paving the way for better support in the future. It's roughly the past month of updates, condensed to remove all of my "wip" "temp" "fix fix fix"-style commits and not pollute the caproto repo history.
Changes
-------
* Get, put, monitor, and RPC support in the server
- No pipelining monitors just yet
- Writes can be canceled by client request
* Split data wrapper utilities into low- and high-level wrappers
- Low level wrapper reasonably easy to build on; has no ties to
`pvaproperty` et al
- Added user-friendlyish ~PVGroup~ `PVAGroup` + `pvaproperty`
- Similar form compared to V3 API
- Batched updates of data by way of async …

[PVA] ENH: server put/monitor/rpc and high-level `pvaproperty` support

---

caproto/pva/_core.py
caproto/pva/_dataclass.py
caproto/pva/_fields.py
caproto/pva/_normative.py
caproto/pva/ioc_examples/group.py
caproto/pva/ioc_examples/normative.py
caproto/pva/server/magic.py
caproto/tests/test_pva_normative.py

(WIP, still playing around with this)
* `PVAGroup` with `attr = pvaproperty(value=0)` implies creating an attribute with `NTScalarInt64` (including the control struct, etc.)
* `PVAGroup` with `attr = pvaproperty(value=[0])` implies creating an attribute with `NTScalarArrayInt64` (including the control struct, etc.)

[PVA] ENH: initial scalar/scalararray normative type support

---

caproto/pva/server/common.py
caproto/server/common.py

Hopefully closes #697 
For reference, `OSError` is an ancestor of `ConnectionError`.
```
+-- OSError
|    +-- BlockingIOError
|    +-- ChildProcessError
|    +-- ConnectionError
|    |    +-- BrokenPipeError
|    |    +-- ConnectionAbortedError
|    |    +-- ConnectionRefusedError
|    |    +-- ConnectionResetError
|    +-- FileExistsError
|    +-- FileNotFoundError
|    +-- InterruptedError
|    +-- IsADirectoryError
|    +-- NotADirectoryError
|    +-- PermissionError
|    +-- ProcessLookupError
|    +-- TimeoutError
```

FIX: ConnectionError -> OSError

---

caproto/server/server.py

Show useful default values with optional macro substitutions. Previously showed "Macro substitution, optional" for each. Now shows something along the lines of:
```
--ev_pv EV_PV         Optional macro substitution, default:
'LCLS:HXR:BEAM:EV'
--pmps_run_pv PMPS_RUN_PV
Optional macro substitution, default:
'PMPS:HXR:AT2L0:RUN'
--pmps_tdes_pv PMPS_TDES_PV
Optional macro substitution, default:
'PMPS:HXR:AT2L0:T_DES'
--motor_prefix MOTOR_PREFIX
Optional macro substitution, default: 'AT2L0:SIM:MMS:'
--autosave_path AUTOSAVE_PATH
Optional macro substitution, default:
'autosave_development.json'
```

MNT: show default value for optional macro substitution

---

caproto/server/server.py
caproto/tests/test_macros.py

This is an optimistic proposal for bringing the double-curly-brace string formatting escape hatch to macro expansion. The optimistic change is to exclude `group.prefix` from macro expansion in `channeldata_from_pvspec()` on the theory that macros have already been expanded in the prefix. The new tests show that this works in simple cases. I welcome suggestions for more test cases.
This PR closes #563.

Avoid multiple passes of macro expansion, such that {{ is sufficient to "escape".

---

doc/source/release-notes.rst

Some comparatively minor fixes that will improve quality of life/reliability in certain scenarios.
(For PCDS, the `OSError` fix will be essential.)

DOC: release notes for bugfix v0.7.1 release

---

caproto/asyncio/client.py
caproto/asyncio/utils.py

Windows-related fixes. More users are trying the asyncio client on Windows and running into strange issues. Hopefully this will fix at least some of them.
Fixes
------
(1) There appears to have been a race for using the socket versus binding it, so `bind()` was moved up to avoid the following exception:
```
[E 11:09:50.604        utils:   61] <caproto.asyncio.utils._DatagramProtocol object at 0x000001F5E4BE8CD0> receive error
File "C:\tools\miniconda3\envs\caproto\lib\asyncio\proactor_events.py", line 566, in _loop_reading
self._read_fut = self._loop._proactor.recvfrom(self._sock,
File "C:\tools\miniconda3\envs\caproto\lib\asyncio\windows_events.py", line 494, in recvfrom
ov.WSARecvFrom(conn.fileno(), nbytes, flags)
OSError: [WinError 10022] An invalid …
```

FIX: win32 bind and shutdown errors in asyncio client

---

caproto/asyncio/client.py

Follow-up on #707. My review comment flagged one of these, but there was a second one as well. Unless there is some reason to treat this one differently, I think the same logic applies.

Log exception for better bug reports.

---

caproto/ioc_examples/scan_rate.py
caproto/server/common.py
caproto/server/server.py

Supersedes #692 
Closes #691 (by allowing both, rather than raising)
Tested locally and now working.

REF: allow for both 'scan' and 'startup' hooks in server

---

caproto/_dbr.py
caproto/threading/client.py
caproto/threading/pyepics_compat.py

Closes #682 
Could use some double-checking and verification, but local testing with `caproto.ioc_examples.enums` proved successful:
```python
In [1]: from caproto.threading.pyepics_compat import PV
In [2]: pv = PV('enum:mbbi')
In [3]: pv.char_value
Out[3]: 'one'
In [4]: pv.enum_strs
Out[4]: ('zero', 'one', '', 'three', 'four')
```

FIX: pyepics compat char_value and enum_strs

---

caproto/ioc_examples/decay.py
caproto/ioc_examples/no_pvproperty.py
caproto/ioc_examples/records.py
caproto/ioc_examples/too_clever/trigger_with_pc.py
caproto/server/server.py
caproto/tests/test_records.py

Background
==========
Users have commented that `PVGroup` is _convoluted and confusing_ (@mattgibbs and others).
While I don't disagree about the convoluted nature, I think the cleanliness of the resulting `PVGroup` classes should be reason enough to forgive the implementation details.  
For those that feel that way, the alternative at the moment is to use `ChannelData` directly. This is fairly barebones and doesn't support any of the nice hooks that `pvproperty` brought along with it.
`PVSpec` was initially written with the idea that `pvproperty`/`PVGroup` could be thrown away and the useful bits could be retained. That work had never been completed until now.
This PR
=======
This PR allows you to use `PVSpec` on its own in a sort of "expert" mode, but still having the …

REF: rework PVSpec instantiation, allowing for use outside of PVGroups

---

caproto/_data.py
caproto/_utils.py
caproto/ioc_examples/big_image_noisy_neighbor.py

Closes #705 
Overview
----------
Supports the numpy array interface to remove a significant ``O(n)``  bottleneck when pre-processing numpy arrays for ``ChannelByte`` instances.  
Notes
------
* To avoid an additional copy on immutable data, set ``value.flags.writeable``  to ``False`` when using compatible numpy arrays.  (#731)
* ``ChannelChar`` will eventually be decoded, so `.tobytes()` is unavoidable - but we can at least let numpy take care of this for us instead of using `map(chr, value)`.

FIX/ENH: attempt to support array interface to remove bottleneck processing numpy arrays

---

.gitignore
caproto/_circuit.py
caproto/_utils.py
caproto/asyncio/client.py
caproto/asyncio/server.py
caproto/asyncio/utils.py
caproto/pva/asyncio/server.py
caproto/server/common.py

_Almost_ entirely does away with `asyncio.Protocol`, favoring the higher-level read/write transports - which eschew callbacks and allow for control flow to go through awaitable methods. I think this is in general much easier to follow. With this, we stand to better capture where exceptions are happening and log more appropriate information.
Though tests are passing locally and on Azure, it would be wise to double-check this on each of our platforms. A mistake here has the potential to hamper IOC functionality, after all.
Closes #680 (at least in my own testing)
Closes #696 
Testing:
* Locally working on Python 3.6 to 3.8 with a Win10 20H2 VM, and macOS as usual.
* Tests are passing now (Linux-based Azure)

MNT: Unify asyncio wrappers

---

doc/source/release-notes.rst

Included unmerged PRs which I've marked in the v0.8.0 milestone. Those will be merged prior to this PR, before a tag and release.

DOC: preliminary v0.8.0 release notes

---

caproto/_data.py
caproto/server/server.py
doc/source/iocs.rst

Mostly docstring updates - `caproto._data` is in a not-as-terrible state with this PR.

MNT/DOC: clean and tweak and add a bunch of docstrings

---

.github/workflows/testing.yml
caproto/asyncio/client.py
caproto/asyncio/server.py
caproto/curio/server.py
caproto/pva/sync/client.py
caproto/sync/client.py
caproto/tests/test_doc_utils.py
caproto/tests/test_threading_client.py
caproto/tests/view_leaks.py
caproto/threading/client.py
caproto/trio/server.py

Notably these do not rely on `conda` and do **not** test with their respective platform's `softIoc` executable like the azure pipelines tests do for Linux. So if they pass, at least caproto itself is internally consistent, but untested with respect to epics-base servers.
Also includes some fixes found along the way:
Closes #747 
Closes #746 
Closes #745 
Closes #748
Long-standing awful test "test_multithreaded_many_write" has been improved here, too. (As much as I like the concept behind that test suite, it's pretty poorly written...)
(Apologies for starting Actions as a push to master; I'm new to it and not sure if there was a way around it. Regardless, this PR should give a good initial first test suite runner)

CI: add basic GitHub actions for Windows and macOS testing

---

caproto/threading/client.py

Internal API, but API nonetheless
Closes #609

API: remove connection_state_callback, access_rights_callback from thread PV init

---

caproto/asyncio/client.py
caproto/threading/client.py

Explanation in #757.
Does not close that issue. Reduces unhelpful spam until we learn more.

MNT: remove quality-of-support message for now

---

.pre-commit-config.yaml
caproto/_data.py
caproto/_dbr.py
caproto/ioc_examples/advanced/raw_timestamp.py
caproto/tests/conftest.py
caproto/tests/test_examples.py
caproto/tests/test_timestamp.py

Closes #770 
Hopefully doesn't break anything. `ChannelData._data[*]` is not intended to be modified by the user, and this PR uses that to its advantage.
I don't particularly like the class `TimeStamp`, but it _is_ already accessible to the user. Added a few convenience methods to it accordingly.
Also - more docstrings and improved ones, based on the `timestamp` change.

ENH/REF: Support raw timestamps in ChannelData

---

doc/source/release-notes.rst

* pyepics compat fix
* Raw timestamp addition
Today is release day 🎆

DOC: release notes for v0.8.1

---

caproto/server/server.py

Fix for issue described in: https://github.com/caproto/caproto/issues/783 .

Updated method get_data_class() in PVSpec so that type maps are correct for read only

---

caproto/threading/client.py

This fixes a problem (#798) where a PV would never reconnect after the connection to the IOC was temporarily interrupted.

Reconnect PV when connection is interrupted

---

doc/source/install.rst

Version 3.8+ is required, according to https://github.com/caproto/caproto/commit/fcf35af6a4de6d730c3155a6619f8cb5565bb6f5

Update required python version in docs

---

caproto/ioc_examples/lakeshore.py

An IOC with a simulated temperature controller and thermal material.
This demonstrates how to do put_completion with a caproto ioc and ophyd device.
Another interesting part of this example is the use of settle_time.  Settle_time allows us to wait an additional amount after the put_completion.  It is used here to wait for the stabilization of the material temperature after the setpoint ramp is complete.
This also includes a simulated material that can be heated/cooled and a PID controller that can be connected to arbitrary systems.  The PIDController has a ramp feature so that the setpoint ramps to the target value gradually.
Here is a plot of the pid controller working:

Lakeshore example with put completion and settle_time

---

.github/workflows/docs.yml
.github/workflows/flake8.yml
.github/workflows/pypi.yml
.github/workflows/testing.yml
.pre-commit-config.yaml
caproto/ioc_examples/fake_motor_record.py
doc/rebuild.sh
doc/source/conf.py
doc/source/example_conf.py
doc/source/example_requirements-docs.txt
doc/source/own_docs.rst
doc/source/release-notes.rst
requirements-doc.txt

* Add Python 3.11 to the testing matrix
* Update pre-commit check versions
* Update all GitHub actions to latest
* Fix flake8 error not previously caught
* Add missing release notes for v1.0.1 (already released)
* Fix up documentation deployment (`doctr-versions-menu` -> [`docs-versions-menu`](https://pypi.org/project/docs-versions-menu/)) and remove all traces of `doctr`

CI: test on py311

---

azure-pipelines.yml

18.04 was removed in December 2022 per https://learn.microsoft.com/en-us/azure/devops/release-notes/2022/sprint-208-update
If this upgrade isn't easy, I'm going to just nuke Azure Pipelines entirely from this repository because it's failing our test suite unnecessarily

CI: move azure pipelines to Ubuntu 22.04

---

caproto/_utils.py
caproto/server/common.py
caproto/trio/server.py

Closes #813 
See the linked issue for further details.
Tested and found to work locally:
* The array slice filter (with two separate monitors)
* The deadband filter
This is fundamental code to caproto's server mechanism, so a detailed/thorough review would be wise and appreciated.

FIX: server subscriptions affecting each other

---

caproto/server/common.py
caproto/tests/issue_797_server.py
caproto/tests/test_events_off.py

Closes issue #797 
This initially was the "alternate" solution: uses only `subscriptions_to_resend` and avoids caching data from dropped subscriptions during the period where events are off (and data gets garbage collected) which became my preferred solution to the issue.
Reproduced with: https://github.com/klauer/issue_797_caproto_subs
Server: `support-ioc.py` (run this first)
Client: `client_issue_797.py` (run this second)
The final result should indicate that each PV saw one subscription total.
caproto master will range from 1 to 19 subscriptions on average.
This PR should bump that up to the expected 20.
This is now part of the test suite in this PR.
Subscription values - generated once and held by way of weakref - were getting cleaned up before the queue had a chance to send them. …

FIX: issue 797 - subscription queue loss with eventsoff/eventson

---

caproto/threading/pyepics_compat.py

`caproto.threading.pyepics_compat.caget_many` inadvertently created a new CA context every time this function was called without an explicitly specified context. With this PR, it instead reuses the default context, like the other functions in the module do.
This closes #824.

Reuse existing context if none is specified

---

caproto/server/conversion.py
caproto/tests/test_server.py

Per the CI:
```
Run flake8 caproto/
caproto/server/conversion.py:184:24: E226 missing whitespace around arithmetic operator
caproto/server/conversion.py:187:29: E226 missing whitespace around arithmetic operator
caproto/server/conversion.py:190:20: E226 missing whitespace around arithmetic operator
caproto/server/conversion.py:191:20: E226 missing whitespace around arithmetic operator
caproto/server/conversion.py:192:20: E226 missing whitespace around arithmetic operator
caproto/server/conversion.py:193:20: E226 missing whitespace around arithmetic operator
caproto/server/conversion.py:194:20: E226 missing whitespace around arithmetic operator
caproto/server/conversion.py:195:20: E226 missing whitespace around arithmetic operator
caproto/tests/test_server.py:212:13: F811 redefinition of …
```

STY: fix flake8 errors

---

.ci/azure_env.sh
.pre-commit-config.yaml
azure-pipelines.yml
caproto/asyncio/server.py
caproto/tests/conftest.py
caproto/tests/epics_test_utils.py
caproto/tests/test_events_off.py
caproto/tests/test_examples.py
caproto/tests/test_pyepics_compat2.py
caproto/tests/test_records.py
caproto/tests/test_repeater.py
caproto/tests/test_server.py
caproto/tests/test_threading_client.py
caproto/threading/pyepics_compat.py

Closes #830
Closes #434 (9f52809b2d2b38c96622d9833220b387c49d2038)
Supersedes #845
* Picks up #845 because curio/trio are not fun to work with in 2024
* Fixes an apparently massive bug in server subscriptions causing test instability
* Debugging led me to [this](https://github.com/caproto/caproto/issues/830#issuecomment-2525303112), and it seems `ensure_future` was the culprit causing the queue items to be dropped when a timeout happened
* That change is [e75cf00](https://github.com/caproto/caproto/pull/854/commits/e75cf005cbbadffbd520e6ab8b53eb7fbcd75117)
* Fixes the worst hit Windows IOCs on 3.12, but also improves stability in all other platforms and versions
* Fixes other test suite bugs, primarily `auto_monitor=True`-related race conditions that we should have caught ages ago
* Fixes …

FIX: asyncio server subscription-related failures and (some) test suite instability

---

caproto/tests/test_pyepics_compat2.py

This new test is being flaky, this is how @klauer fixed the other ones.

CI: force not using monitor in tests

---

caproto/ioc_examples/pathological/spoof_beamline.py

This adds two functionalities:
- The ability to add custom interaction between channels
- A default `ChannelString` for `PortName` to handle area detector plugins
An example of the spoof beamline that has custom interaction can be found here: 
https://github.com/thomashopkins32/CMS_profile_collection/blob/master/iocs/spoof_beamline.py#L62-L89

Spoof Beamline: Add ability to define custom logic and fabricate PortName channel

---

caproto/threading/pyepics_compat.py

`pyepics_compat.caget_many` currently uses `PV._default_context` which is a cached_property and cannot be used without an instance of `PV`.
This uses `_make_context` instead which is also cached as well and used internally by `PV._default_context`.
This fixes caproto/caproto#863

Use _make_context in caget_many instead of PV._default_context

---

caproto/tests/test_pyepics_compat.py
caproto/tests/test_pyepics_compat2.py
caproto/threading/pyepics_compat.py

Currently, doing
```
PV._default_context
```
fails because it is actually an instance method rather than a class method. It is used this way in a couple of places:
- https://github.com/caproto/caproto/blob/284568779305335fed069459999a65e933cff93f/caproto/threading/pyepics_compat.py#L1043
- https://github.com/bluesky/ophyd/blob/main/ophyd/_caproto_shim.py#L202
This PR makes it a proper class method with caching.
Here is a small script I wrote to test this:
```python
import time
import functools
@functools.lru_cache(1)
def context():
time.sleep(5)
return Context({"name": "test"})
class Context:
def __init__(self, context):
self.context = context
def __str__(self):
return f"Context: {self.context}"
class TestClass:
@classmethod
@property
@functools.cache
def _default_cls_context(cls):
return …
```

Make PV._default_context a public class method
